# Generated by Django 4.2.7 on 2025-11-05 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="品牌名称"),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="品牌代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="品牌描述")),
                (
                    "logo",
                    models.ImageField(blank=True, upload_to="brands/", verbose_name="品牌Logo"),
                ),
                ("website", models.URLField(blank=True, verbose_name="官方网站")),
                (
                    "country",
                    models.CharField(blank=True, max_length=50, verbose_name="国家/地区"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
            options={
                "verbose_name": "品牌",
                "verbose_name_plural": "品牌",
                "db_table": "products_brand",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                ("name", models.CharField(max_length=200, verbose_name="产品名称")),
                (
                    "code",
                    models.CharField(max_length=100, unique=True, verbose_name="产品编码"),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="条形码",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("material", "原材料"),
                            ("semi_finished", "半成品"),
                            ("finished", "成品"),
                            ("service", "服务"),
                            ("virtual", "虚拟产品"),
                        ],
                        default="finished",
                        max_length=20,
                        verbose_name="产品类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "正常"),
                            ("inactive", "停用"),
                            ("discontinued", "停产"),
                            ("development", "开发中"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="产品描述")),
                (
                    "specifications",
                    models.TextField(blank=True, verbose_name="产品规格"),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, verbose_name="型号"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="重量(kg)",
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="长度(cm)",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="宽度(cm)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="高度(cm)",
                    ),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="成本价",
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="销售价",
                    ),
                ),
                (
                    "min_stock",
                    models.PositiveIntegerField(default=0, verbose_name="最小库存"),
                ),
                (
                    "max_stock",
                    models.PositiveIntegerField(default=0, verbose_name="最大库存"),
                ),
                (
                    "reorder_point",
                    models.PositiveIntegerField(default=0, verbose_name="再订货点"),
                ),
                (
                    "main_image",
                    models.ImageField(blank=True, upload_to="products/", verbose_name="主图"),
                ),
                (
                    "warranty_period",
                    models.PositiveIntegerField(default=0, verbose_name="保修期(月)"),
                ),
                (
                    "shelf_life",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="保质期(天)"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "产品",
                "verbose_name_plural": "产品",
                "db_table": "products_product",
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="属性名称")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="属性代码"),
                ),
                (
                    "attribute_type",
                    models.CharField(
                        choices=[
                            ("text", "文本"),
                            ("number", "数字"),
                            ("boolean", "布尔值"),
                            ("date", "日期"),
                            ("choice", "选择"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="属性类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="属性描述")),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="是否必填"),
                ),
                (
                    "is_filterable",
                    models.BooleanField(default=False, verbose_name="是否可筛选"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
            options={
                "verbose_name": "产品属性",
                "verbose_name_plural": "产品属性",
                "db_table": "products_attribute",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                ("value", models.TextField(verbose_name="属性值")),
            ],
            options={
                "verbose_name": "产品属性值",
                "verbose_name_plural": "产品属性值",
                "db_table": "products_attribute_value",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="分类代码"),
                ),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="categories/", verbose_name="分类图片"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "verbose_name": "产品分类",
                "verbose_name_plural": "产品分类",
                "db_table": "products_category",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/images/", verbose_name="图片"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="图片标题"),
                ),
                ("description", models.TextField(blank=True, verbose_name="图片描述")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="是否主图"),
                ),
            ],
            options={
                "verbose_name": "产品图片",
                "verbose_name_plural": "产品图片",
                "db_table": "products_image",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("cost", "成本价"),
                            ("selling", "销售价"),
                            ("wholesale", "批发价"),
                            ("retail", "零售价"),
                        ],
                        max_length=20,
                        verbose_name="价格类型",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="价格"),
                ),
                ("effective_date", models.DateField(verbose_name="生效日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                ("reason", models.TextField(blank=True, verbose_name="调价原因")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否生效"),
                ),
            ],
            options={
                "verbose_name": "产品价格历史",
                "verbose_name_plural": "产品价格历史",
                "db_table": "products_price_history",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="单位名称"),
                ),
                (
                    "symbol",
                    models.CharField(max_length=10, unique=True, verbose_name="单位符号"),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("basic", "基本单位"),
                            ("weight", "重量单位"),
                            ("length", "长度单位"),
                            ("area", "面积单位"),
                            ("volume", "体积单位"),
                            ("time", "时间单位"),
                            ("count", "计数单位"),
                        ],
                        default="basic",
                        max_length=20,
                        verbose_name="单位类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="单位描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
            ],
            options={
                "verbose_name": "计量单位",
                "verbose_name_plural": "计量单位",
                "db_table": "products_unit",
            },
        ),
    ]
