# Generated by Django 4.2.7 on 2025-11-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "delivery_number",
                    models.CharField(max_length=100, unique=True, verbose_name="发货单号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparing", "准备中"),
                            ("ready", "待发货"),
                            ("shipped", "已发货"),
                            ("in_transit", "运输中"),
                            ("delivered", "已送达"),
                            ("failed", "配送失败"),
                            ("returned", "已退回"),
                        ],
                        default="preparing",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("planned_date", models.DateField(verbose_name="计划发货日期")),
                (
                    "actual_date",
                    models.DateField(blank=True, null=True, verbose_name="实际发货日期"),
                ),
                (
                    "delivered_date",
                    models.DateField(blank=True, null=True, verbose_name="送达日期"),
                ),
                ("shipping_address", models.TextField(verbose_name="收货地址")),
                (
                    "shipping_contact",
                    models.CharField(max_length=100, verbose_name="收货联系人"),
                ),
                (
                    "shipping_phone",
                    models.CharField(max_length=20, verbose_name="收货电话"),
                ),
                (
                    "shipping_method",
                    models.CharField(blank=True, max_length=100, verbose_name="配送方式"),
                ),
                (
                    "carrier",
                    models.CharField(blank=True, max_length=100, verbose_name="承运商"),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=100, verbose_name="快递单号"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "发货单",
                "verbose_name_plural": "发货单",
                "db_table": "sales_delivery",
                "ordering": ["-planned_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="发货数量"),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=100, verbose_name="批次号"),
                ),
                (
                    "serial_numbers",
                    models.TextField(
                        blank=True,
                        help_text="多个序列号用换行分隔",
                        verbose_name="序列号",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "发货明细",
                "verbose_name_plural": "发货明细",
                "db_table": "sales_delivery_item",
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "quote_number",
                    models.CharField(max_length=100, unique=True, verbose_name="报价单号"),
                ),
                (
                    "quote_type",
                    models.CharField(
                        choices=[("domestic", "国内报价"), ("overseas", "海外报价")],
                        default="domestic",
                        max_length=20,
                        verbose_name="报价类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("sent", "已发送"),
                            ("accepted", "已接受"),
                            ("rejected", "已拒绝"),
                            ("expired", "已过期"),
                            ("converted", "已转订单"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("quote_date", models.DateField(verbose_name="报价日期")),
                ("valid_until", models.DateField(verbose_name="有效期至")),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=10, verbose_name="币种"),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        max_digits=10,
                        verbose_name="汇率",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="小计"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="税率(%)",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="税额"
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="折扣率(%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="折扣金额",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="总金额",
                    ),
                ),
                (
                    "total_amount_cny",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="自动转换为人民币",
                        max_digits=12,
                        verbose_name="总金额(CNY)",
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(blank=True, max_length=200, verbose_name="付款条件"),
                ),
                (
                    "delivery_terms",
                    models.CharField(blank=True, max_length=200, verbose_name="交货条件"),
                ),
                (
                    "warranty_terms",
                    models.TextField(blank=True, verbose_name="质保条款"),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, verbose_name="客户询价号"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "销售报价",
                "verbose_name_plural": "销售报价",
                "db_table": "sales_quote",
                "ordering": ["-quote_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="数量"),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="单价"),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="折扣率(%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="折扣金额",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="行总计",
                    ),
                ),
                (
                    "lead_time",
                    models.PositiveIntegerField(default=0, verbose_name="交货周期(天)"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
            ],
            options={
                "verbose_name": "报价明细",
                "verbose_name_plural": "报价明细",
                "db_table": "sales_quote_item",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "order_number",
                    models.CharField(max_length=100, unique=True, verbose_name="订单号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("confirmed", "已确认"),
                            ("in_production", "生产中"),
                            ("ready_to_ship", "待发货"),
                            ("shipped", "已发货"),
                            ("delivered", "已交付"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "未付款"),
                            ("partial", "部分付款"),
                            ("paid", "已付款"),
                            ("overdue", "逾期"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="付款状态",
                    ),
                ),
                ("order_date", models.DateField(verbose_name="订单日期")),
                (
                    "required_date",
                    models.DateField(blank=True, null=True, verbose_name="要求交期"),
                ),
                (
                    "promised_date",
                    models.DateField(blank=True, null=True, verbose_name="承诺交期"),
                ),
                (
                    "shipped_date",
                    models.DateField(blank=True, null=True, verbose_name="发货日期"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="小计"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="税率(%)",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="税额"
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="折扣率(%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="折扣金额",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="运费"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="总金额",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=10, verbose_name="币种"),
                ),
                (
                    "shipping_address",
                    models.TextField(blank=True, verbose_name="收货地址"),
                ),
                (
                    "shipping_contact",
                    models.CharField(blank=True, max_length=100, verbose_name="收货联系人"),
                ),
                (
                    "shipping_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="收货电话"),
                ),
                (
                    "shipping_method",
                    models.CharField(blank=True, max_length=100, verbose_name="配送方式"),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=100, verbose_name="快递单号"),
                ),
                (
                    "payment_terms",
                    models.CharField(blank=True, max_length=200, verbose_name="付款条件"),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, verbose_name="付款方式"),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, verbose_name="客户订单号"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="内部备注"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
            ],
            options={
                "verbose_name": "销售订单",
                "verbose_name_plural": "销售订单",
                "db_table": "sales_order",
                "ordering": ["-order_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="数量"),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="单价"),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="折扣率(%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="折扣金额",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="行总计",
                    ),
                ),
                (
                    "delivered_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="已交付数量",
                    ),
                ),
                (
                    "required_date",
                    models.DateField(blank=True, null=True, verbose_name="要求交期"),
                ),
                (
                    "produced_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="已生产数量",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
            ],
            options={
                "verbose_name": "销售订单明细",
                "verbose_name_plural": "销售订单明细",
                "db_table": "sales_order_item",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SalesReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "return_number",
                    models.CharField(max_length=100, unique=True, verbose_name="退货单号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("approved", "已批准"),
                            ("received", "已收货"),
                            ("processed", "已处理"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("defective", "产品缺陷"),
                            ("wrong_item", "发错货"),
                            ("damaged", "运输损坏"),
                            ("not_needed", "不再需要"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="退货原因",
                    ),
                ),
                ("return_date", models.DateField(verbose_name="退货日期")),
                (
                    "received_date",
                    models.DateField(blank=True, null=True, verbose_name="收货日期"),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="退款金额",
                    ),
                ),
                (
                    "restocking_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="重新入库费",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "销售退货",
                "verbose_name_plural": "销售退货",
                "db_table": "sales_return",
                "ordering": ["-return_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="退货数量"),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="退货单价"),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="行总计",
                    ),
                ),
                (
                    "condition",
                    models.CharField(blank=True, max_length=100, verbose_name="货物状态"),
                ),
                (
                    "disposition",
                    models.CharField(blank=True, max_length=100, verbose_name="处理方式"),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=100, verbose_name="批次号"),
                ),
                ("serial_numbers", models.TextField(blank=True, verbose_name="序列号")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "退货明细",
                "verbose_name_plural": "退货明细",
                "db_table": "sales_return_item",
            },
        ),
    ]
