# Generated by Django 4.2.7 on 2025-11-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_remove_salesorder_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="payment_terms",
            field=models.CharField(
                blank=True, help_text="从客户信息自动带出", max_length=50, verbose_name="付款方式"
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="payment_terms",
            field=models.CharField(
                blank=True, help_text="从客户信息自动带出", max_length=50, verbose_name="付款方式"
            ),
        ),
    ]
