# Generated by Django 4.2.7 on 2025-11-06 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0005_alter_quote_payment_terms_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模板名称")),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("quote_domestic", "报价单-国内"),
                            ("quote_overseas", "报价单-海外"),
                            ("sales_order", "销售订单"),
                            ("purchase_order", "采购订单"),
                        ],
                        max_length=20,
                        verbose_name="模板类型",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="默认模板"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="BetterLaser 激光科技有限公司",
                        max_length=200,
                        verbose_name="公司名称",
                    ),
                ),
                (
                    "company_address",
                    models.CharField(blank=True, max_length=500, verbose_name="公司地址"),
                ),
                (
                    "company_phone",
                    models.CharField(blank=True, max_length=50, verbose_name="联系电话"),
                ),
                (
                    "company_email",
                    models.CharField(blank=True, max_length=100, verbose_name="电子邮箱"),
                ),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="print_templates/logos/",
                        verbose_name="公司Logo",
                    ),
                ),
                (
                    "layout_config",
                    models.JSONField(default=dict, verbose_name="布局配置"),
                ),
                (
                    "custom_css",
                    models.TextField(blank=True, help_text="自定义CSS样式", verbose_name="自定义样式"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "打印模板",
                "verbose_name_plural": "打印模板",
                "db_table": "sales_print_template",
                "ordering": ["-is_default", "template_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["template_type", "is_active"],
                        name="sales_print_templat_67c3a5_idx",
                    ),
                    models.Index(
                        fields=["is_default", "is_active"],
                        name="sales_print_is_defa_9ba899_idx",
                    ),
                ],
            },
        ),
    ]
