# Generated by Django 4.2.7 on 2025-11-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0006_printtemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteitem",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=13,
                help_text="增值税税率，默认13%",
                max_digits=5,
                verbose_name="税率(%)",
            ),
        ),
    ]
