# Generated by Django 4.2.7 on 2025-11-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_quoteitem_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='invoice_status',
            field=models.CharField(choices=[('not_invoiced', '未开票'), ('partial_invoiced', '部分开票'), ('invoiced', '已开票')], default='not_invoiced', max_length=20, verbose_name='开票状态'),
        ),
    ]
