# Generated by Django 4.2.7 on 2025-11-09 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0010_quoteitem_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultTemplateMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("quote_domestic", "报价单-国内"),
                            ("quote_overseas", "报价单-海外"),
                            ("sales_order", "销售订单"),
                            ("delivery", "发货单"),
                            ("sales_return", "销售退货"),
                            ("purchase_order", "采购订单"),
                            ("purchase_receipt", "采购入库"),
                            ("purchase_return", "采购退货"),
                            ("stock_in", "入库单"),
                            ("stock_out", "出库单"),
                            ("stock_transfer", "调拨单"),
                            ("stock_check", "盘点单"),
                            ("invoice", "发票"),
                            ("payment", "付款单"),
                            ("receipt", "收款单"),
                        ],
                        db_index=True,
                        help_text="为该单据类型设置默认打印模板",
                        max_length=50,
                        unique=True,
                        verbose_name="单据类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "默认模板配置",
                "verbose_name_plural": "默认模板配置",
                "db_table": "sales_default_template_mapping",
                "ordering": ["document_type"],
            },
        ),
        migrations.AlterModelOptions(
            name="printtemplate",
            options={
                "ordering": ["template_category", "name"],
                "verbose_name": "打印模板",
                "verbose_name_plural": "打印模板",
            },
        ),
        migrations.RemoveIndex(
            model_name="printtemplate",
            name="sales_print_templat_67c3a5_idx",
        ),
        migrations.RemoveIndex(
            model_name="printtemplate",
            name="sales_print_is_defa_9ba899_idx",
        ),
        migrations.RemoveField(
            model_name="printtemplate",
            name="is_default",
        ),
        migrations.RemoveField(
            model_name="printtemplate",
            name="template_type",
        ),
        migrations.AddField(
            model_name="printtemplate",
            name="suitable_for",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='JSON数组格式，例如：["quote", "sales_order"]。用于在打印时优先显示更相关的模板',
                verbose_name="适用单据类型",
            ),
        ),
        migrations.AddField(
            model_name="printtemplate",
            name="template_category",
            field=models.CharField(
                choices=[
                    ("sales", "📊 销售类"),
                    ("purchase", "🛒 采购类"),
                    ("inventory", "📦 库存类"),
                    ("finance", "💰 财务类"),
                    ("other", "📋 其他类"),
                ],
                db_index=True,
                default="sales",
                help_text="模板所属的大类，同类别的模板可以共享使用",
                max_length=20,
                verbose_name="模板类别",
            ),
        ),
        migrations.AddIndex(
            model_name="printtemplate",
            index=models.Index(
                fields=["template_category", "is_active"], name="sales_print_templat_aec1a1_idx"
            ),
        ),
        migrations.AddField(
            model_name="defaulttemplatemapping",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="defaulttemplatemapping",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="删除人",
            ),
        ),
        migrations.AddField(
            model_name="defaulttemplatemapping",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="该单据类型的默认模板，打印时自动选中",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_documents",
                to="sales.printtemplate",
                verbose_name="默认模板",
            ),
        ),
        migrations.AddField(
            model_name="defaulttemplatemapping",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
    ]
