# Generated by Django 4.2.7 on 2025-11-13 13:43
# Modified to only update Django state, not database

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0011_defaulttemplatemapping_alter_printtemplate_options_and_more"),
        ("core", "0004_move_print_templates_from_sales"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                # State: 从 sales app 的状态中移除这两个模型
                migrations.RemoveField(
                    model_name="printtemplate",
                    name="created_by",
                ),
                migrations.RemoveField(
                    model_name="printtemplate",
                    name="deleted_by",
                ),
                migrations.RemoveField(
                    model_name="printtemplate",
                    name="updated_by",
                ),
                migrations.DeleteModel(
                    name="DefaultTemplateMapping",
                ),
                migrations.DeleteModel(
                    name="PrintTemplate",
                ),
            ],
            database_operations=[
                # Database: 不做任何操作,因为表已经在 core 迁移中被重命名
                # 这里使用空操作即可
            ],
        ),
    ]
