# Generated by Django 5.0.9 on 2026-01-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_add_partial_delivery_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitem',
            name='actual_shipped_quantity',
            field=models.IntegerField(default=0, help_text='实际已发货数量（支持部分发货）', verbose_name='实际发货数量'),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='quantity',
            field=models.IntegerField(help_text='计划发货数量', verbose_name='计划发货数量'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='quantity',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='delivered_quantity',
            field=models.IntegerField(default=0, verbose_name='已交付数量'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='produced_quantity',
            field=models.IntegerField(default=0, verbose_name='已生产数量'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='quantity',
            field=models.IntegerField(verbose_name='数量'),
        ),
    ]
