# Generated by Django 5.0.9 on 2026-02-10 05:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0018_auto_20260204_2152"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="salesorder",
            name="sales_order_cust_status_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="salesorder",
            name="sales_order_created_at_desc_idx",
        ),
    ]
