# Generated by Django 4.2.7 on 2025-12-19 00:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_remove_customer_customer_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="fax",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phone",
        ),
    ]
