# Generated by Django 4.2.7 on 2025-11-10 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0003_remove_purchaseorder_payment_method_and_more"),
        ("finance", "0003_invoice_invoiceitem_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplieraccount",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "供应商账款",
                "verbose_name_plural": "供应商账款",
            },
        ),
        migrations.AddField(
            model_name="supplieraccount",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_accounts",
                to="finance.invoice",
                verbose_name="关联发票",
            ),
        ),
        migrations.AddField(
            model_name="supplieraccount",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待付款"),
                    ("partially_paid", "部分付款"),
                    ("paid", "已付清"),
                    ("overdue", "已逾期"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="supplieraccount",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="未付余额"
            ),
        ),
        migrations.AlterField(
            model_name="supplieraccount",
            name="invoice_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="应付金额"
            ),
        ),
        migrations.AlterField(
            model_name="supplieraccount",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_accounts",
                to="purchase.purchaseorder",
                verbose_name="采购订单",
            ),
        ),
        migrations.AddIndex(
            model_name="supplieraccount",
            index=models.Index(
                fields=["supplier", "status"], name="finance_sup_supplie_8f8e72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplieraccount",
            index=models.Index(fields=["due_date"], name="finance_sup_due_dat_99d54e_idx"),
        ),
    ]
