# Generated by Django 4.2.7 on 2025-11-10 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0004_alter_supplieraccount_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("balance_sheet", "资产负债表"),
                            ("income_statement", "利润表"),
                            ("cash_flow", "现金流量表"),
                            ("trial_balance", "科目余额表"),
                            ("account_ledger", "科目明细账"),
                        ],
                        max_length=30,
                        verbose_name="报表类型",
                    ),
                ),
                ("report_date", models.DateField(help_text="资产负债表的截止日期", verbose_name="报表日期")),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="利润表和现金流量表的起始日期", null=True, verbose_name="开始日期"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="利润表和现金流量表的截止日期", null=True, verbose_name="结束日期"
                    ),
                ),
                ("report_data", models.JSONField(help_text="JSON格式存储报表详细数据", verbose_name="报表数据")),
                (
                    "total_assets",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="总资产",
                    ),
                ),
                (
                    "total_liabilities",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="总负债",
                    ),
                ),
                (
                    "total_equity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="所有者权益",
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        null=True,
                        verbose_name="净利润",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True, verbose_name="生成时间")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="生成人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "财务报表",
                "verbose_name_plural": "财务报表",
                "db_table": "finance_financial_report",
                "ordering": ["-report_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["report_type", "report_date"], name="finance_fin_report__d3ed23_idx"
                    ),
                    models.Index(fields=["report_date"], name="finance_fin_report__eb8fd1_idx"),
                ],
            },
        ),
    ]
