# Generated by Django 4.2.7 on 2025-11-14 13:58

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0005_add_financial_report_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例如：增值税13%、增值税9%",
                        max_length=100,
                        unique=True,
                        verbose_name="税率名称",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="例如：VAT_13、VAT_9",
                        max_length=50,
                        unique=True,
                        verbose_name="税率代码",
                    ),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("vat", "增值税"),
                            ("consumption", "消费税"),
                            ("business", "营业税"),
                            ("customs", "关税"),
                            ("income", "所得税"),
                            ("other", "其他"),
                        ],
                        default="vat",
                        max_length=20,
                        verbose_name="税种",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="税率值（0-1之间的小数，如0.13表示13%）",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="税率",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="每种税种只能有一个默认税率",
                        verbose_name="是否默认税率",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="说明该税率的适用范围和条件",
                        verbose_name="适用说明",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True,
                        help_text="税率开始生效的日期",
                        null=True,
                        verbose_name="生效日期",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="税率失效的日期（如果有）",
                        null=True,
                        verbose_name="失效日期",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, help_text="数字越小越靠前", verbose_name="排序"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "税率",
                "verbose_name_plural": "税率",
                "db_table": "finance_tax_rate",
                "ordering": ["tax_type", "sort_order", "-rate"],
                "indexes": [
                    models.Index(
                        fields=["tax_type", "is_active"],
                        name="finance_tax_tax_typ_97b1da_idx",
                    ),
                    models.Index(fields=["is_default"], name="finance_tax_is_defa_73fe96_idx"),
                ],
            },
        ),
    ]
