# Generated by Django 4.2.7 on 2025-11-17 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0003_alter_supplier_payment_terms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0003_alter_customer_payment_terms"),
        ("finance", "0006_taxrate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierPrepayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="预付金额"),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="剩余余额"),
                ),
                ("currency", models.CharField(default="CNY", max_length=10, verbose_name="币种")),
                ("paid_date", models.DateField(verbose_name="付款日期")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prepayments",
                        to="suppliers.supplier",
                        verbose_name="供应商",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "供应商预付款",
                "verbose_name_plural": "供应商预付款",
                "db_table": "finance_supplier_prepayment",
            },
        ),
        migrations.CreateModel(
            name="CustomerPrepayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="预收金额"),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="剩余余额"),
                ),
                ("currency", models.CharField(default="CNY", max_length=10, verbose_name="币种")),
                ("received_date", models.DateField(verbose_name="收到日期")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prepayments",
                        to="customers.customer",
                        verbose_name="客户",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "客户预收款",
                "verbose_name_plural": "客户预收款",
                "db_table": "finance_customer_prepayment",
            },
        ),
    ]
