# Generated by Django 5.0.9 on 2026-01-16 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0010_update_payment_methods"),
        ("suppliers", "0005_remove_supplier_contact_person_remove_supplier_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="quantity",
            field=models.IntegerField(verbose_name="数量"),
        ),
        migrations.AlterField(
            model_name="supplieraccount",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="实际应付-已核销",
                max_digits=12,
                verbose_name="未付余额",
            ),
        ),
        migrations.AlterField(
            model_name="supplieraccount",
            name="invoice_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="累计正应付+累计负应付",
                max_digits=12,
                verbose_name="实际应付金额",
            ),
        ),
        migrations.AlterField(
            model_name="supplieraccount",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="累计已核销金额",
                max_digits=12,
                verbose_name="已核销金额",
            ),
        ),
        migrations.CreateModel(
            name="SupplierAccountDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                (
                    "detail_number",
                    models.CharField(max_length=100, unique=True, verbose_name="明细单号"),
                ),
                (
                    "detail_type",
                    models.CharField(
                        choices=[("receipt", "收货正应付"), ("return", "退货负应付")],
                        max_length=20,
                        verbose_name="明细类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待核销"), ("partial", "部分核销"), ("allocated", "已核销")],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="正应付为正，负应付为负",
                        max_digits=12,
                        verbose_name="应付金额",
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="已核销金额"
                    ),
                ),
                ("business_date", models.DateField(help_text="收货/退货日期", verbose_name="业务日期")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "parent_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="归集到应付主单",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="details",
                        to="finance.supplieraccount",
                        verbose_name="应付主单",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_details",
                        to="purchase.purchaseorder",
                        verbose_name="采购订单",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        help_text="收货正应付时关联",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_details",
                        to="purchase.purchasereceipt",
                        verbose_name="收货单",
                    ),
                ),
                (
                    "return_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="退货负应付时关联",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_details",
                        to="purchase.purchasereturn",
                        verbose_name="退货单",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_details",
                        to="suppliers.supplier",
                        verbose_name="供应商",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "供应商应付明细",
                "verbose_name_plural": "供应商应付明细",
                "db_table": "finance_supplier_account_detail",
                "ordering": ["-business_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["supplier", "status"], name="finance_sup_supplie_441144_idx"
                    ),
                    models.Index(
                        fields=["purchase_order", "detail_type"],
                        name="finance_sup_purchas_277414_idx",
                    ),
                    models.Index(fields=["receipt"], name="finance_sup_receipt_6e2d23_idx"),
                    models.Index(fields=["return_order"], name="finance_sup_return__cd79ee_idx"),
                    models.Index(fields=["parent_account"], name="finance_sup_parent__877ea9_idx"),
                ],
            },
        ),
    ]
