# Generated by Django 5.0.9 on 2026-02-04 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0011_alter_invoiceitem_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprepayment",
            name="is_consolidated",
            field=models.BooleanField(default=False, verbose_name="是否合并记录"),
        ),
        migrations.AddField(
            model_name="customerprepayment",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_from",
                to="finance.customerprepayment",
                verbose_name="合并到",
            ),
        ),
        migrations.AddField(
            model_name="customerprepayment",
            name="status",
            field=models.CharField(
                choices=[("active", "活跃"), ("merged", "已合并"), ("exhausted", "已用完")],
                default="active",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AddField(
            model_name="supplierprepayment",
            name="is_consolidated",
            field=models.BooleanField(default=False, verbose_name="是否合并记录"),
        ),
        migrations.AddField(
            model_name="supplierprepayment",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_from",
                to="finance.supplierprepayment",
                verbose_name="合并到",
            ),
        ),
        migrations.AddField(
            model_name="supplierprepayment",
            name="status",
            field=models.CharField(
                choices=[("active", "活跃"), ("merged", "已合并"), ("exhausted", "已用完")],
                default="active",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
