# Generated by Django 5.0.9 on 2026-02-04 13:53
# 性能优化: 为SupplierAccount添加索引以提升查询性能

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0012_add_prepayment_consolidation_fields"),
    ]

    operations = [
        # SupplierAccount索引 - 优化供应商账款列表查询性能
        # 用于优化: filter(supplier=X, status=Y).filter(due_date__lt=)
        migrations.AddIndex(
            model_name="supplieraccount",
            index=models.Index(
                fields=["supplier", "status", "due_date"],
                name="supplier_account_sup_status_due_idx",
            ),
        ),
    ]
