# Generated by Django 5.0.9 on 2026-02-10 05:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0013_auto_20260204_2153"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="supplieraccount",
            name="supplier_account_sup_status_due_idx",
        ),
    ]
