# Generated by Django 5.0.9 on 2026-01-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_platform_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description_en',
            field=models.TextField(blank=True, help_text='英文公司描述', verbose_name='Company Description (English)'),
        ),
    ]
