"""
Inventory app URLs.
"""
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

app_name = 'inventory'

router = DefaultRouter()

urlpatterns = [
    path('api/', include(router.urls)),
    path('', views.stock_list, name='stock_root'),
    path('stocks/', views.stock_list, name='stock_list'),
    path('stocks/<int:pk>/', views.stock_detail, name='stock_detail'),
    path('transactions/', views.transaction_list, name='transaction_list'),
    path('warehouses/', views.warehouse_list, name='warehouse_list'),
    path('warehouses/create/', views.warehouse_create, name='warehouse_create'),
    path('warehouses/<int:pk>/', views.warehouse_detail, name='warehouse_detail'),
    path('warehouses/<int:pk>/edit/', views.warehouse_update, name='warehouse_update'),
    path('warehouses/<int:warehouse_pk>/locations/create/', views.location_create, name='location_create'),
    path('adjustments/', views.adjustment_list, name='adjustment_list'),
    path('adjustments/create/', views.adjustment_create, name='adjustment_create'),
    path('adjustments/<int:pk>/', views.adjustment_detail, name='adjustment_detail'),
    path('adjustments/<int:pk>/edit/', views.adjustment_update, name='adjustment_update'),
    path('adjustments/<int:pk>/delete/', views.adjustment_delete, name='adjustment_delete'),
    path('adjustments/<int:pk>/approve/', views.adjustment_approve, name='adjustment_approve'),
    path('transfers/', views.transfer_list, name='transfer_list'),
    path('transfers/create/', views.transfer_create, name='transfer_create'),
    path('transfers/<int:pk>/', views.transfer_detail, name='transfer_detail'),
    path('transfers/<int:pk>/edit/', views.transfer_update, name='transfer_update'),
    path('transfers/<int:pk>/delete/', views.transfer_delete, name='transfer_delete'),
    path('transfers/<int:pk>/submit/', views.transfer_submit, name='transfer_submit'),
    path('transfers/<int:pk>/approve/', views.transfer_approve, name='transfer_approve'),
    path('transfers/<int:pk>/ship/', views.transfer_ship, name='transfer_ship'),
    path('transfers/<int:pk>/receive/', views.transfer_receive, name='transfer_receive'),
    path('transfers/<int:pk>/cancel/', views.transfer_cancel, name='transfer_cancel'),
    path('counts/', views.count_list, name='count_list'),
    path('counts/create/', views.count_create, name='count_create'),
    path('counts/<int:pk>/', views.count_detail, name='count_detail'),
    path('counts/<int:pk>/edit/', views.count_update, name='count_update'),
    path('counts/<int:pk>/delete/', views.count_delete, name='count_delete'),
    path('counts/<int:pk>/start/', views.count_start, name='count_start'),
    path('counts/<int:pk>/complete/', views.count_complete, name='count_complete'),
    path('counts/<int:pk>/cancel/', views.count_cancel, name='count_cancel'),
    path('inbounds/', views.inbound_list, name='inbound_list'),
    path('inbounds/create/', views.inbound_create, name='inbound_create'),
    path('inbounds/<int:pk>/', views.inbound_detail, name='inbound_detail'),
    path('inbounds/<int:pk>/edit/', views.inbound_update, name='inbound_update'),
    path('inbounds/<int:pk>/delete/', views.inbound_delete, name='inbound_delete'),
    path('inbounds/<int:pk>/approve/', views.inbound_approve, name='inbound_approve'),
    path('inbounds/<int:pk>/complete/', views.inbound_complete, name='inbound_complete'),
    path('inbounds/<int:pk>/cancel/', views.inbound_cancel, name='inbound_cancel'),
    path('outbounds/', views.outbound_list, name='outbound_list'),
    path('outbounds/create/', views.outbound_create, name='outbound_create'),
    path('outbounds/<int:pk>/', views.outbound_detail, name='outbound_detail'),
    path('outbounds/<int:pk>/edit/', views.outbound_update, name='outbound_update'),
    path('outbounds/<int:pk>/delete/', views.outbound_delete, name='outbound_delete'),
    path('outbounds/<int:pk>/approve/', views.outbound_approve, name='outbound_approve'),
    path('outbounds/<int:pk>/complete/', views.outbound_complete, name='outbound_complete'),
    path('outbounds/<int:pk>/cancel/', views.outbound_cancel, name='outbound_cancel'),
    path('reports/orders/', views.inventory_order_report, name='inventory_order_report'),
    path('reports/stock-summary/', views.stock_summary_report, name='report_stock_summary'),
    path('reports/stock-transaction/', views.stock_transaction_report, name='report_stock_transaction'),
    path('reports/stock-alert/', views.stock_alert_report, name='report_stock_alert'),
    path('reports/inbound-outbound-statistics/', views.inbound_outbound_statistics, name='report_inbound_outbound_statistics'),
    path('import/', views.stock_import, name='stock_import'),
    path('import/submit/', views.stock_import_submit, name='stock_import_submit'),
    path('data-import/', views.data_import, name='data_import'),
    path('data-export/', views.data_export, name='data_export'),
]
