# Generated by Django 5.0.9 on 2026-01-31 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ecomm_sync", "0004_alter_platformaccount_platform_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogisticsCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("name", models.CharField(max_length=200, verbose_name="物流公司名称")),
                (
                    "code",
                    models.CharField(
                        help_text="唯一标识，如SF、YTO、DHL等",
                        max_length=50,
                        unique=True,
                        verbose_name="物流公司代码",
                    ),
                ),
                (
                    "api_endpoint",
                    models.URLField(
                        blank=True, help_text="官方API地址", max_length=500, verbose_name="API端点"
                    ),
                ),
                (
                    "tracking_url_template",
                    models.CharField(
                        blank=True,
                        help_text="物流查询URL模板，如https://www.sf-express.com/waybill/#search/all/{tracking_number}",
                        max_length=500,
                        verbose_name="查询URL模板",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("tier_1", "完整API支持（创建运单、查询轨迹、打印面单、取消运单）"),
                            ("tier_2", "部分API支持（仅查询轨迹）"),
                            ("tier_3", "仅网页查询（爬虫支持）"),
                        ],
                        default="tier_1",
                        help_text="API支持级别",
                        max_length=10,
                        verbose_name="支持级别",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "api_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="API配置信息，如app_id、app_secret等",
                        verbose_name="API配置",
                    ),
                ),
                ("logo_url", models.URLField(blank=True, max_length=500, verbose_name="Logo URL")),
                ("website", models.URLField(blank=True, max_length=500, verbose_name="官网地址")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "物流公司",
                "verbose_name_plural": "物流公司",
                "db_table": "logistics_company",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ShippingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                (
                    "tracking_number",
                    models.CharField(db_index=True, max_length=200, verbose_name="快递单号"),
                ),
                (
                    "shipping_status",
                    models.CharField(
                        choices=[
                            ("pending", "待发货"),
                            ("shipped", "已发货"),
                            ("in_transit", "运输中"),
                            ("out_for_delivery", "派送中"),
                            ("delivered", "已签收"),
                            ("failed", "配送失败"),
                            ("returned", "已退货"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="物流状态",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="物流总费用",
                        max_digits=10,
                        verbose_name="物流费用",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="订单总重量",
                        max_digits=10,
                        null=True,
                        verbose_name="重量(kg)",
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="订单总体积",
                        max_digits=10,
                        null=True,
                        verbose_name="体积(m³)",
                    ),
                ),
                ("shipped_at", models.DateTimeField(blank=True, null=True, verbose_name="发货时间")),
                ("delivered_at", models.DateTimeField(blank=True, null=True, verbose_name="签收时间")),
                (
                    "last_track_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后查询时间"),
                ),
                ("note", models.TextField(blank=True, verbose_name="备注")),
                (
                    "waybill_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="waybills/%Y/%m/", verbose_name="面单图片"
                    ),
                ),
                (
                    "waybill_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="waybills/pdf/%Y/%m/", verbose_name="面单PDF"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "logistics_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipping_orders",
                        to="logistics.logisticscompany",
                        verbose_name="物流公司",
                    ),
                ),
                (
                    "platform_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_orders",
                        to="ecomm_sync.platformorder",
                        verbose_name="平台订单",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "物流订单",
                "verbose_name_plural": "物流订单",
                "db_table": "logistics_shipping_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LogisticsCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("freight", "运费"),
                            ("fuel_surcharge", "燃油费"),
                            ("remote_area_fee", "偏远费"),
                            ("cod_fee", "货到付款费"),
                            ("insurance", "保险费"),
                            ("package_fee", "包装费"),
                            ("other", "其他费用"),
                        ],
                        max_length=50,
                        verbose_name="费用类型",
                    ),
                ),
                (
                    "cost_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="费用金额"),
                ),
                ("cost_date", models.DateField(verbose_name="费用日期")),
                ("description", models.CharField(blank=True, max_length=500, verbose_name="费用描述")),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, help_text="物流公司提供的费用参考号", max_length=200, verbose_name="参考号"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "shipping_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="logistics.shippingorder",
                        verbose_name="物流订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "物流成本",
                "verbose_name_plural": "物流成本",
                "db_table": "logistics_cost",
                "ordering": ["-cost_date"],
            },
        ),
        migrations.CreateModel(
            name="TrackingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("track_time", models.DateTimeField(db_index=True, verbose_name="轨迹时间")),
                (
                    "track_status",
                    models.CharField(db_index=True, max_length=100, verbose_name="轨迹状态"),
                ),
                (
                    "track_location",
                    models.CharField(blank=True, max_length=500, verbose_name="轨迹地点"),
                ),
                ("track_description", models.TextField(blank=True, verbose_name="轨迹描述")),
                ("operator", models.CharField(blank=True, max_length=200, verbose_name="操作人")),
                ("raw_data", models.JSONField(blank=True, default=dict, verbose_name="原始数据")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "shipping_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_infos",
                        to="logistics.shippingorder",
                        verbose_name="物流订单",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "物流轨迹",
                "verbose_name_plural": "物流轨迹",
                "db_table": "logistics_tracking_info",
                "ordering": ["track_time"],
            },
        ),
        migrations.CreateModel(
            name="WaybillTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("name", models.CharField(max_length=200, verbose_name="模板名称")),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("thermal_100x180", "热敏纸 100x180mm"),
                            ("thermal_100x100", "热敏纸 100x100mm"),
                            ("a4", "A4纸"),
                            ("a5", "A5纸"),
                            ("custom", "自定义"),
                        ],
                        default="thermal_100x180",
                        max_length=50,
                        verbose_name="模板类型",
                    ),
                ),
                ("template_html", models.TextField(verbose_name="HTML模板")),
                ("css_style", models.TextField(blank=True, verbose_name="CSS样式")),
                ("is_default", models.BooleanField(default=False, verbose_name="是否默认模板")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="waybill_templates/thumbnails/",
                        verbose_name="缩略图",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "logistics_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waybill_templates",
                        to="logistics.logisticscompany",
                        verbose_name="物流公司",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "物流面单模板",
                "verbose_name_plural": "物流面单模板",
                "db_table": "logistics_waybill_template",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="shippingorder",
            index=models.Index(fields=["tracking_number"], name="logistics_s_trackin_f83490_idx"),
        ),
        migrations.AddIndex(
            model_name="shippingorder",
            index=models.Index(fields=["shipping_status"], name="logistics_s_shippin_877b94_idx"),
        ),
        migrations.AddIndex(
            model_name="shippingorder",
            index=models.Index(fields=["-shipped_at"], name="logistics_s_shipped_ba2cfd_idx"),
        ),
        migrations.AddIndex(
            model_name="shippingorder",
            index=models.Index(
                fields=["platform_order", "-shipped_at"], name="logistics_s_platfor_0cddad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shippingorder",
            index=models.Index(
                fields=["logistics_company", "shipping_status"],
                name="logistics_s_logisti_b476aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="logisticscost",
            index=models.Index(
                fields=["shipping_order", "cost_date"], name="logistics_c_shippin_393440_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logisticscost",
            index=models.Index(
                fields=["cost_type", "-cost_date"], name="logistics_c_cost_ty_bde896_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trackinginfo",
            index=models.Index(
                fields=["shipping_order", "-track_time"], name="logistics_t_shippin_3b7f2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trackinginfo",
            index=models.Index(
                fields=["track_status", "-track_time"], name="logistics_t_track_s_28cdd4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="waybilltemplate",
            unique_together={("logistics_company", "name")},
        ),
    ]
