# Generated by Django 4.2.7 on 2025-12-19 00:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0004_remove_supplier_suppliers_s_supplie_c9bf31_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="email",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="fax",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="phone",
        ),
    ]
