# Generated by Django 5.0.9 on 2026-01-31 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_platform_shop_and_more'),
        ('ecomm_sync', '0003_extend_platform_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformaccount',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.platform', verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='ecommproduct',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecomm_products', to='core.platform', verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='platformorder',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.platform', verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='apicalllog',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to='core.platform', verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='syncstrategy',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='core.platform', verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='core.platform', verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='stocksyncqueue',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_sync_queues', to='core.platform', verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='core.platform', verbose_name='平台'),
        ),
        migrations.RemoveField(
            model_name='wooshopconfig',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='wooshopconfig',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='wooshopconfig',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='EcommPlatform',
        ),
        migrations.DeleteModel(
            name='WooShopConfig',
        ),
    ]
