# Generated by Django 4.2.7 on 2025-11-11 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_payment_terms'),
        ('suppliers', '0003_alter_supplier_payment_terms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_initial'),
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='入库单号')),
                ('order_type', models.CharField(choices=[('purchase', '采购入库'), ('return', '退货入库'), ('transfer', '调拨入库'), ('other', '其他入库')], max_length=20, verbose_name='入库类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已审核'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('order_date', models.DateField(verbose_name='入库日期')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='参考单号')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='参考类型')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='参考ID')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_inbound_orders', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier', verbose_name='供应商')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '入库单',
                'verbose_name_plural': '入库单',
                'db_table': 'inventory_inbound_order',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='出库单号')),
                ('order_type', models.CharField(choices=[('sales', '销售出库'), ('production', '生产出库'), ('transfer', '调拨出库'), ('other', '其他出库')], max_length=20, verbose_name='出库类型')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已审核'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('order_date', models.DateField(verbose_name='出库日期')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='参考单号')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='参考类型')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='参考ID')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_outbound_orders', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='客户')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='仓库')),
            ],
            options={
                'verbose_name': '出库单',
                'verbose_name_plural': '出库单',
                'db_table': 'inventory_outbound_order',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='出库数量')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='批次号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location', verbose_name='库位')),
                ('outbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.outboundorder', verbose_name='出库单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='产品')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '出库明细',
                'verbose_name_plural': '出库明细',
                'db_table': 'inventory_outbound_order_item',
            },
        ),
        migrations.CreateModel(
            name='InboundOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='入库数量')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='批次号')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='过期日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('inbound_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inboundorder', verbose_name='入库单')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location', verbose_name='库位')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='产品')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '入库明细',
                'verbose_name_plural': '入库明细',
                'db_table': 'inventory_inbound_order_item',
            },
        ),
    ]
