# Generated by Django 5.0.9 on 2026-01-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_warehouse_warehouse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='标识该调拨单是否由系统自动生成（如借用转采购）。系统生成的调拨单不允许编辑和反审核。', verbose_name='系统自动生成'),
        ),
        migrations.AlterField(
            model_name='inboundorderitem',
            name='quantity',
            field=models.IntegerField(verbose_name='入库数量'),
        ),
        migrations.AlterField(
            model_name='inventorystock',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='库存数量'),
        ),
        migrations.AlterField(
            model_name='inventorystock',
            name='reserved_quantity',
            field=models.IntegerField(default=0, verbose_name='预留数量'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='quantity',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjusted_quantity',
            field=models.IntegerField(verbose_name='调整后数量'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='difference',
            field=models.IntegerField(default=0, verbose_name='差异数量'),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='original_quantity',
            field=models.IntegerField(verbose_name='原数量'),
        ),
        migrations.AlterField(
            model_name='stockcountitem',
            name='counted_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='盘点数量'),
        ),
        migrations.AlterField(
            model_name='stockcountitem',
            name='difference',
            field=models.IntegerField(default=0, verbose_name='差异数量'),
        ),
        migrations.AlterField(
            model_name='stockcountitem',
            name='system_quantity',
            field=models.IntegerField(verbose_name='系统数量'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='received_quantity',
            field=models.IntegerField(default=0, verbose_name='收货数量'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='requested_quantity',
            field=models.IntegerField(verbose_name='申请数量'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='shipped_quantity',
            field=models.IntegerField(default=0, verbose_name='发货数量'),
        ),
    ]
