# Generated by Django 5.0.1 on 2026-02-10

from django.db import migrations


def update_inbound_order_types(apps, schema_editor):
    """更新入库单类型"""
    InboundOrder = apps.get_model("inventory", "InboundOrder")

    # 将现有的 "return" 类型更改为 "sales_return"
    InboundOrder.objects.filter(order_type="return").update(order_type="sales_return")


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_auto_20260204_2153"),
    ]

    operations = [
        migrations.RunPython(update_inbound_order_types, migrations.RunPython.noop),
    ]
