# Generated by Django 5.0.9 on 2026-02-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_update_order_types"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="inventorystock",
            name="inventory_s_quantit_287c3e_idx",
        ),
        migrations.RemoveIndex(
            model_name="inventorystock",
            name="inventory_s_created_103d57_idx",
        ),
        migrations.RemoveIndex(
            model_name="inventorystock",
            name="inventory_s_is_low__fdb1c3_idx",
        ),
        migrations.RemoveIndex(
            model_name="inventorystock",
            name="inventory_stock_low_stock_warehouse_idx",
        ),
        migrations.AlterField(
            model_name="inboundorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("purchase", "采购入库"),
                    ("sales_return", "销售退货入库"),
                    ("transfer", "调拨入库"),
                    ("other", "其他入库"),
                ],
                max_length=20,
                verbose_name="入库类型",
            ),
        ),
        migrations.AlterField(
            model_name="outboundorder",
            name="order_type",
            field=models.CharField(
                choices=[
                    ("sales", "销售出库"),
                    ("purchase_return", "采购退货出库"),
                    ("production", "生产出库"),
                    ("transfer", "调拨出库"),
                    ("other", "其他出库"),
                ],
                max_length=20,
                verbose_name="出库类型",
            ),
        ),
    ]
