# Generated by Django 5.0.9 on 2026-02-01 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0011_add_company_description_en"),
        ("ecomm_sync", "0006_alter_platformaccount_account_type"),
        ("products", "0004_add_default_unit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("name", models.CharField(max_length=200, verbose_name="仪表盘名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "layout",
                    models.JSONField(
                        blank=True, default=dict, help_text="组件布局", verbose_name="布局配置"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="公开仪表盘对所有用户可见", verbose_name="是否公开"
                    ),
                ),
                (
                    "allowed_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="accessible_dashboards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="允许访问的用户",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "仪表盘",
                "verbose_name_plural": "仪表盘",
                "db_table": "bi_dashboard",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("name", models.CharField(max_length=200, verbose_name="组件名称")),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("metric", "指标卡"),
                            ("chart", "图表"),
                            ("table", "表格"),
                            ("list", "列表"),
                        ],
                        max_length=20,
                        verbose_name="组件类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "data_source",
                    models.CharField(help_text="模型或查询方法", max_length=200, verbose_name="数据源"),
                ),
                ("data_params", models.JSONField(blank=True, default=dict, verbose_name="数据参数")),
                (
                    "display_config",
                    models.JSONField(
                        blank=True, default=dict, help_text="图表类型、颜色等", verbose_name="显示配置"
                    ),
                ),
                (
                    "refresh_interval",
                    models.PositiveIntegerField(
                        default=300, help_text="0表示不自动刷新", verbose_name="刷新间隔(秒)"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, help_text="仪表盘中的位置", max_length=100, verbose_name="位置"
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        default=4, help_text="栅格系统宽度，最大12", verbose_name="宽度"
                    ),
                ),
                ("height", models.PositiveIntegerField(default=3, verbose_name="高度")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "仪表盘组件",
                "verbose_name_plural": "仪表盘组件",
                "db_table": "bi_dashboard_widget",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardWidgetConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("config", models.JSONField(blank=True, default=dict, verbose_name="组件配置")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="顺序")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widget_configs",
                        to="bi.dashboard",
                        verbose_name="仪表盘",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "widget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_configs",
                        to="bi.dashboardwidget",
                        verbose_name="组件",
                    ),
                ),
            ],
            options={
                "verbose_name": "仪表盘组件配置",
                "verbose_name_plural": "仪表盘组件配置",
                "db_table": "bi_dashboard_widget_config",
                "ordering": ["order"],
                "unique_together": {("dashboard", "widget")},
            },
        ),
        migrations.AddField(
            model_name="dashboard",
            name="widgets",
            field=models.ManyToManyField(
                related_name="dashboards",
                through="bi.DashboardWidgetConfig",
                to="bi.dashboardwidget",
                verbose_name="组件",
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("name", models.CharField(max_length=200, verbose_name="报表名称")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("sales", "销售报表"),
                            ("order", "订单报表"),
                            ("inventory", "库存报表"),
                            ("platform", "平台对比报表"),
                            ("product", "商品报表"),
                            ("customer", "客户报表"),
                        ],
                        max_length=20,
                        verbose_name="报表类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="报表描述")),
                (
                    "filters_config",
                    models.JSONField(blank=True, default=dict, verbose_name="过滤条件配置"),
                ),
                ("columns_config", models.JSONField(blank=True, default=list, verbose_name="列配置")),
                ("group_by", models.JSONField(blank=True, default=list, verbose_name="分组配置")),
                ("sort_by", models.JSONField(blank=True, default=list, verbose_name="排序配置")),
                ("is_scheduled", models.BooleanField(default=False, verbose_name="是否定时生成")),
                (
                    "schedule_crontab",
                    models.CharField(blank=True, max_length=100, verbose_name="调度Crontab"),
                ),
                (
                    "last_generated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后生成时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.platform",
                        verbose_name="平台",
                    ),
                ),
                (
                    "platform_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="ecomm_sync.platformaccount",
                        verbose_name="平台账号",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "报表",
                "verbose_name_plural": "报表",
                "db_table": "bi_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("data", models.JSONField(default=dict, verbose_name="报表数据")),
                ("row_count", models.PositiveIntegerField(default=0, verbose_name="数据行数")),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="开始日期")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="结束日期")),
                ("generated_at", models.DateTimeField(auto_now_add=True, verbose_name="生成时间")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_records",
                        to="bi.report",
                        verbose_name="报表",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "报表数据",
                "verbose_name_plural": "报表数据",
                "db_table": "bi_report_data",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("report_date", models.DateField(db_index=True, verbose_name="报表日期")),
                (
                    "report_period",
                    models.CharField(
                        default="daily",
                        help_text="daily=日, weekly=周, monthly=月",
                        max_length=20,
                        verbose_name="报表周期",
                    ),
                ),
                ("total_orders", models.PositiveIntegerField(default=0, verbose_name="总订单数")),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="总金额"
                    ),
                ),
                ("total_quantity", models.PositiveIntegerField(default=0, verbose_name="总商品数")),
                (
                    "avg_order_value",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="平均订单金额"
                    ),
                ),
                ("paid_orders", models.PositiveIntegerField(default=0, verbose_name="已付款订单")),
                ("shipped_orders", models.PositiveIntegerField(default=0, verbose_name="已发货订单")),
                ("delivered_orders", models.PositiveIntegerField(default=0, verbose_name="已送达订单")),
                ("cancelled_orders", models.PositiveIntegerField(default=0, verbose_name="已取消订单")),
                ("refunded_orders", models.PositiveIntegerField(default=0, verbose_name="已退款订单")),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="百分比",
                        max_digits=5,
                        verbose_name="转化率",
                    ),
                ),
                (
                    "repeat_purchase_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="百分比",
                        max_digits=5,
                        verbose_name="复购率",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_summaries",
                        to="core.platform",
                        verbose_name="平台",
                    ),
                ),
                (
                    "platform_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_summaries",
                        to="ecomm_sync.platformaccount",
                        verbose_name="平台账号",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "销售汇总",
                "verbose_name_plural": "销售汇总",
                "db_table": "bi_sales_summary",
                "ordering": ["-report_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("current_stock", models.PositiveIntegerField(default=0, verbose_name="当前库存")),
                ("safety_stock", models.PositiveIntegerField(default=0, verbose_name="安全库存")),
                ("max_stock", models.PositiveIntegerField(default=0, verbose_name="最大库存")),
                (
                    "turnover_days",
                    models.IntegerField(default=0, help_text="库存周转天数", verbose_name="周转天数"),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="周转率"
                    ),
                ),
                (
                    "avg_daily_sales",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="日均销量"
                    ),
                ),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("normal", "正常"),
                            ("low", "低库存"),
                            ("out", "缺货"),
                            ("overstock", "积压"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="库存状态",
                    ),
                ),
                (
                    "days_of_stock",
                    models.IntegerField(default=0, help_text="当前库存可销售天数", verbose_name="可销天数"),
                ),
                (
                    "stock_value",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="库存价值"
                    ),
                ),
                (
                    "avg_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="平均成本"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_analysis",
                        to="core.platform",
                        verbose_name="平台",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_analysis",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_analysis",
                        to="core.shop",
                        verbose_name="仓库",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存分析",
                "verbose_name_plural": "库存分析",
                "db_table": "bi_inventory_analysis",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["stock_status"], name="bi_inventor_stock_s_aaa91e_idx"),
                    models.Index(fields=["days_of_stock"], name="bi_inventor_days_of_e3d1f8_idx"),
                    models.Index(
                        fields=["product", "-created_at"], name="bi_inventor_product_1edb47_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlatformComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("report_date", models.DateField(db_index=True, verbose_name="报表日期")),
                (
                    "report_period",
                    models.CharField(default="daily", max_length=20, verbose_name="报表周期"),
                ),
                ("order_count", models.PositiveIntegerField(default=0, verbose_name="订单数")),
                (
                    "order_growth_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="订单增长率"
                    ),
                ),
                (
                    "sales_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="销售金额"
                    ),
                ),
                (
                    "sales_growth_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="销售增长率"
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="转化率"
                    ),
                ),
                (
                    "avg_order_value",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="平均订单金额"
                    ),
                ),
                (
                    "sales_rank",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="销售排名"),
                ),
                (
                    "order_rank",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="订单排名"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_data",
                        to="core.platform",
                        verbose_name="平台",
                    ),
                ),
                (
                    "platform_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparison_data",
                        to="ecomm_sync.platformaccount",
                        verbose_name="平台账号",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "平台对比",
                "verbose_name_plural": "平台对比",
                "db_table": "bi_platform_comparison",
                "ordering": ["-report_date", "-sales_amount"],
                "indexes": [
                    models.Index(
                        fields=["report_date", "-sales_amount"],
                        name="bi_platform_report__9f7783_idx",
                    ),
                    models.Index(
                        fields=["report_date", "-order_count"],
                        name="bi_platform_report__be0868_idx",
                    ),
                ],
                "unique_together": {
                    ("platform", "platform_account", "report_date", "report_period")
                },
            },
        ),
        migrations.CreateModel(
            name="ProductSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                ("report_date", models.DateField(db_index=True, verbose_name="报表日期")),
                (
                    "report_period",
                    models.CharField(default="daily", max_length=20, verbose_name="报表周期"),
                ),
                ("sold_quantity", models.PositiveIntegerField(default=0, verbose_name="销售数量")),
                (
                    "sales_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="销售金额"
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="利润"
                    ),
                ),
                ("order_count", models.PositiveIntegerField(default=0, verbose_name="订单数")),
                ("return_count", models.PositiveIntegerField(default=0, verbose_name="退货数")),
                (
                    "return_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="退货率"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_sales",
                        to="core.platform",
                        verbose_name="平台",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_data",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品销售数据",
                "verbose_name_plural": "商品销售数据",
                "db_table": "bi_product_sales",
                "ordering": ["-report_date", "-sales_amount"],
                "indexes": [
                    models.Index(
                        fields=["report_date", "-sales_amount"],
                        name="bi_product__report__48c5e6_idx",
                    ),
                    models.Index(
                        fields=["product", "-report_date"], name="bi_product__product_a90b21_idx"
                    ),
                ],
                "unique_together": {("product", "platform", "report_date", "report_period")},
            },
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_type", "platform"], name="bi_report_report__9a297f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["created_by"], name="bi_report_created_2a00d4_idx"),
        ),
        migrations.AddIndex(
            model_name="reportdata",
            index=models.Index(
                fields=["report", "-generated_at"], name="bi_report_d_report__b15e62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salessummary",
            index=models.Index(
                fields=["report_date", "-report_period"], name="bi_sales_su_report__40bfd0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salessummary",
            unique_together={("platform", "platform_account", "report_date", "report_period")},
        ),
    ]
