# Generated by Django 4.2.7 on 2025-11-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "order_number",
                    models.CharField(max_length=100, unique=True, verbose_name="采购单号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("pending", "待审核"),
                            ("approved", "已审核"),
                            ("sent", "已发送"),
                            ("confirmed", "已确认"),
                            ("partial_received", "部分收货"),
                            ("received", "已收货"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "未付款"),
                            ("partial", "部分付款"),
                            ("paid", "已付款"),
                            ("overdue", "逾期"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="付款状态",
                    ),
                ),
                ("order_date", models.DateField(verbose_name="订单日期")),
                (
                    "required_date",
                    models.DateField(blank=True, null=True, verbose_name="要求交期"),
                ),
                (
                    "promised_date",
                    models.DateField(blank=True, null=True, verbose_name="承诺交期"),
                ),
                (
                    "received_date",
                    models.DateField(blank=True, null=True, verbose_name="收货日期"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="小计"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="税率(%)",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="税额"
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="折扣率(%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="折扣金额",
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="运费"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="总金额",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=10, verbose_name="币种"),
                ),
                (
                    "delivery_address",
                    models.TextField(blank=True, verbose_name="收货地址"),
                ),
                (
                    "delivery_contact",
                    models.CharField(blank=True, max_length=100, verbose_name="收货联系人"),
                ),
                (
                    "delivery_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="收货电话"),
                ),
                (
                    "payment_terms",
                    models.CharField(blank=True, max_length=200, verbose_name="付款条件"),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, verbose_name="付款方式"),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, verbose_name="供应商订单号"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "internal_notes",
                    models.TextField(blank=True, verbose_name="内部备注"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
            ],
            options={
                "verbose_name": "采购订单",
                "verbose_name_plural": "采购订单",
                "db_table": "purchase_order",
                "ordering": ["-order_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="数量"),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="单价"),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="折扣率(%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="折扣金额",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="行总计",
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="已收货数量",
                    ),
                ),
                (
                    "required_date",
                    models.DateField(blank=True, null=True, verbose_name="要求交期"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
            ],
            options={
                "verbose_name": "采购订单明细",
                "verbose_name_plural": "采购订单明细",
                "db_table": "purchase_order_item",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "receipt_number",
                    models.CharField(max_length=100, unique=True, verbose_name="收货单号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("received", "已收货"),
                            ("inspected", "已检验"),
                            ("accepted", "已验收"),
                            ("rejected", "已拒收"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("receipt_date", models.DateField(verbose_name="收货日期")),
                (
                    "inspection_date",
                    models.DateField(blank=True, null=True, verbose_name="检验日期"),
                ),
                (
                    "delivery_note",
                    models.CharField(blank=True, max_length=100, verbose_name="送货单号"),
                ),
                (
                    "carrier",
                    models.CharField(blank=True, max_length=100, verbose_name="承运商"),
                ),
                (
                    "vehicle_number",
                    models.CharField(blank=True, max_length=20, verbose_name="车牌号"),
                ),
                (
                    "driver_name",
                    models.CharField(blank=True, max_length=100, verbose_name="司机姓名"),
                ),
                (
                    "driver_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="司机电话"),
                ),
                (
                    "overall_quality",
                    models.CharField(blank=True, max_length=100, verbose_name="整体质量"),
                ),
                (
                    "quality_notes",
                    models.TextField(blank=True, verbose_name="质量备注"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "采购收货",
                "verbose_name_plural": "采购收货",
                "db_table": "purchase_receipt",
                "ordering": ["-receipt_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "received_quantity",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="收货数量"),
                ),
                (
                    "accepted_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="验收数量",
                    ),
                ),
                (
                    "rejected_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=12,
                        verbose_name="拒收数量",
                    ),
                ),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("passed", "合格"),
                            ("failed", "不合格"),
                            ("pending", "待检"),
                            ("conditional", "有条件接收"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="质量状态",
                    ),
                ),
                (
                    "quality_notes",
                    models.TextField(blank=True, verbose_name="质量备注"),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=100, verbose_name="批次号"),
                ),
                (
                    "serial_numbers",
                    models.TextField(
                        blank=True,
                        help_text="多个序列号用换行分隔",
                        verbose_name="序列号",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(blank=True, null=True, verbose_name="过期日期"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "收货明细",
                "verbose_name_plural": "收货明细",
                "db_table": "purchase_receipt_item",
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "request_number",
                    models.CharField(max_length=100, unique=True, verbose_name="申请单号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("submitted", "已提交"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                            ("ordered", "已下单"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("normal", "普通"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                ("request_date", models.DateField(verbose_name="申请日期")),
                ("required_date", models.DateField(verbose_name="需要日期")),
                ("purpose", models.CharField(max_length=200, verbose_name="用途")),
                (
                    "justification",
                    models.TextField(blank=True, verbose_name="申请理由"),
                ),
                (
                    "estimated_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="预估总额",
                    ),
                ),
                (
                    "budget_code",
                    models.CharField(blank=True, max_length=100, verbose_name="预算科目"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="拒绝原因"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "采购申请",
                "verbose_name_plural": "采购申请",
                "db_table": "purchase_request",
                "ordering": ["-request_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="申请数量"),
                ),
                (
                    "estimated_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="预估单价",
                    ),
                ),
                (
                    "estimated_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="预估总价",
                    ),
                ),
                (
                    "specifications",
                    models.TextField(blank=True, verbose_name="规格要求"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="排序"),
                ),
            ],
            options={
                "verbose_name": "采购申请明细",
                "verbose_name_plural": "采购申请明细",
                "db_table": "purchase_request_item",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "return_number",
                    models.CharField(max_length=100, unique=True, verbose_name="退货单号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("approved", "已批准"),
                            ("shipped", "已发货"),
                            ("completed", "已完成"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("defective", "产品缺陷"),
                            ("wrong_item", "发错货"),
                            ("damaged", "运输损坏"),
                            ("not_ordered", "未订购"),
                            ("overdelivery", "超量交货"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="退货原因",
                    ),
                ),
                ("return_date", models.DateField(verbose_name="退货日期")),
                (
                    "shipped_date",
                    models.DateField(blank=True, null=True, verbose_name="发货日期"),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="退款金额",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "采购退货",
                "verbose_name_plural": "采购退货",
                "db_table": "purchase_return",
                "ordering": ["-return_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="退货数量"),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="退货单价"),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="行总计",
                    ),
                ),
                (
                    "condition",
                    models.CharField(blank=True, max_length=100, verbose_name="货物状态"),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=100, verbose_name="批次号"),
                ),
                ("serial_numbers", models.TextField(blank=True, verbose_name="序列号")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "退货明细",
                "verbose_name_plural": "退货明细",
                "db_table": "purchase_return_item",
            },
        ),
    ]
