# Generated by Django 4.2.7 on 2025-11-11 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0003_alter_supplier_payment_terms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0003_inboundorder_outboundorder_outboundorderitem_and_more"),
        ("departments", "0002_initial"),
        ("products", "0002_initial"),
        ("purchase", "0003_remove_purchaseorder_payment_method_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                (
                    "inquiry_number",
                    models.CharField(max_length=100, unique=True, verbose_name="询价单号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("sent", "已发送"),
                            ("quoted", "已报价"),
                            ("selected", "已选定"),
                            ("ordered", "已下单"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("inquiry_date", models.DateField(verbose_name="询价日期")),
                ("deadline", models.DateField(verbose_name="报价截止日期")),
                ("required_date", models.DateField(blank=True, null=True, verbose_name="需求日期")),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("description", models.TextField(blank=True, verbose_name="需求描述")),
                ("delivery_address", models.TextField(blank=True, verbose_name="收货地址")),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tt_100", "T/T 100%"),
                            ("net_30", "NET 30 EOM."),
                            ("net_60", "NET 60 EOM."),
                            ("30_70", "30% Adv,70% B4 SHPT.30%+70%"),
                            ("cash", "Cash"),
                            ("be", "B/E"),
                        ],
                        max_length=50,
                        verbose_name="付款方式",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                ("internal_notes", models.TextField(blank=True, verbose_name="内部备注")),
                (
                    "buyer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_inquiries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="采购员",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="departments.department",
                        verbose_name="申请部门",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="purchase.purchaseorder",
                        verbose_name="转换的采购单",
                    ),
                ),
                (
                    "purchase_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="purchase.purchaserequest",
                        verbose_name="采购申请",
                    ),
                ),
            ],
            options={
                "verbose_name": "采购询价",
                "verbose_name_plural": "采购询价",
                "db_table": "purchase_inquiry",
                "ordering": ["-inquiry_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseInquiryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="需求数量"),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="期望的单价",
                        max_digits=12,
                        verbose_name="目标价格",
                    ),
                ),
                ("specifications", models.TextField(blank=True, verbose_name="规格要求")),
                ("quality_requirements", models.TextField(blank=True, verbose_name="质量要求")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase.purchaseinquiry",
                        verbose_name="询价单",
                    ),
                ),
                (
                    "preferred_supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="suppliers.supplier",
                        verbose_name="首选供应商",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="产品",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "询价单明细",
                "verbose_name_plural": "询价单明细",
                "db_table": "purchase_inquiry_item",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="SupplierQuotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                (
                    "quotation_number",
                    models.CharField(max_length=100, unique=True, verbose_name="报价单号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待报价"),
                            ("submitted", "已提交"),
                            ("selected", "已选定"),
                            ("rejected", "已拒绝"),
                            ("expired", "已过期"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("quotation_date", models.DateField(verbose_name="报价日期")),
                ("valid_until", models.DateField(verbose_name="有效期至")),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=100, verbose_name="联系人"),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=20, verbose_name="联系电话")),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="联系邮箱"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="小计"
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="税率(%)"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="税额"
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="运费"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="总金额"
                    ),
                ),
                ("currency", models.CharField(default="CNY", max_length=10, verbose_name="币种")),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tt_100", "T/T 100%"),
                            ("net_30", "NET 30 EOM."),
                            ("net_60", "NET 60 EOM."),
                            ("30_70", "30% Adv,70% B4 SHPT.30%+70%"),
                            ("cash", "Cash"),
                            ("be", "B/E"),
                        ],
                        max_length=50,
                        verbose_name="付款方式",
                    ),
                ),
                ("delivery_period", models.IntegerField(default=0, verbose_name="交货期(天)")),
                ("warranty_period", models.IntegerField(default=0, verbose_name="质保期(月)")),
                (
                    "quality_certificate",
                    models.CharField(blank=True, max_length=200, verbose_name="质量证书"),
                ),
                (
                    "evaluation_score",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="0-10分",
                        max_digits=3,
                        verbose_name="综合评分",
                    ),
                ),
                ("evaluation_notes", models.TextField(blank=True, verbose_name="评估备注")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                ("rejection_reason", models.TextField(blank=True, verbose_name="拒绝原因")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotations",
                        to="purchase.purchaseinquiry",
                        verbose_name="询价单",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotations",
                        to="suppliers.supplier",
                        verbose_name="供应商",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "供应商报价",
                "verbose_name_plural": "供应商报价",
                "db_table": "supplier_quotation",
                "ordering": ["-quotation_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierQuotationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                (
                    "quantity",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="报价数量"),
                ),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="单价"),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=5, verbose_name="折扣率(%)"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="折扣金额"
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="行总计"
                    ),
                ),
                ("brand", models.CharField(blank=True, max_length=100, verbose_name="品牌")),
                ("model", models.CharField(blank=True, max_length=100, verbose_name="型号")),
                ("origin", models.CharField(blank=True, max_length=100, verbose_name="产地")),
                ("delivery_period", models.IntegerField(default=0, verbose_name="交货期(天)")),
                (
                    "min_order_quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="最小订购量"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="排序")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "inquiry_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchase.purchaseinquiryitem",
                        verbose_name="询价明细",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="产品",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase.supplierquotation",
                        verbose_name="报价单",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "报价明细",
                "verbose_name_plural": "报价明细",
                "db_table": "supplier_quotation_item",
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddField(
            model_name="purchaseinquiry",
            name="selected_quotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_inquiries",
                to="purchase.supplierquotation",
                verbose_name="选定报价",
            ),
        ),
        migrations.AddField(
            model_name="purchaseinquiry",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="更新人",
            ),
        ),
        migrations.AddField(
            model_name="purchaseinquiry",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.warehouse",
                verbose_name="收货仓库",
            ),
        ),
    ]
