# Generated by Django 4.2.7 on 2026-01-06 11:57

from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("suppliers", "0002_initial"),
        ("products", "0002_initial"),
        ("purchase", "0005_qualityinspection_qualityinspectiontemplate_and_more"),
    ]

    operations = [
        # ==================== 字段重命名操作 ====================
        migrations.RenameField(
            model_name="purchaseorderitem",
            old_name="order",
            new_name="purchase_order",
        ),
        migrations.RenameField(
            model_name="purchaserequestitem",
            old_name="request",
            new_name="purchase_request",
        ),
        migrations.RenameField(
            model_name="purchasereturnitem",
            old_name="return_order",
            new_name="purchase_return",
        ),
        migrations.RenameField(
            model_name="qualityinspection",
            old_name="failed_quantity",
            new_name="fail_quantity",
        ),
        migrations.RenameField(
            model_name="qualityinspection",
            old_name="passed_quantity",
            new_name="pass_quantity",
        ),
        # ==================== 创建 Borrow 模型 ====================
        migrations.CreateModel(
            name="Borrow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                (
                    "borrow_number",
                    models.CharField(max_length=100, unique=True, verbose_name="借用单号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("borrowed", "借用中"),
                            ("partially_returned", "部分归还"),
                            ("fully_returned", "全部归还"),
                            ("converting", "转换中"),
                            ("converted", "已转采购"),
                            ("cancelled", "已取消"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("borrow_date", models.DateField(verbose_name="借用日期")),
                (
                    "expected_return_date",
                    models.DateField(blank=True, null=True, verbose_name="预计归还日期"),
                ),
                (
                    "conversion_approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="转采购审核时间"),
                ),
                ("conversion_notes", models.TextField(blank=True, verbose_name="转采购备注")),
                ("purpose", models.TextField(blank=True, verbose_name="借用目的")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "buyer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="borrows_as_buyer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="经办人",
                    ),
                ),
                (
                    "conversion_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="borrow_conversion_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="转采购审核人",
                    ),
                ),
                (
                    "converted_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_borrow",
                        to="purchase.purchaseorder",
                        verbose_name="转换的采购订单",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrows",
                        to="suppliers.supplier",
                        verbose_name="供应商",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "采购借用单",
                "verbose_name_plural": "采购借用单",
                "db_table": "purchase_borrow",
                "ordering": ["-borrow_date", "-created_at"],
            },
        ),
        # ==================== 创建 BorrowItem 模型 ====================
        migrations.CreateModel(
            name="BorrowItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="删除时间")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[MinValueValidator(0)],
                        verbose_name="借用数量",
                    ),
                ),
                (
                    "returned_quantity",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="已归还数量"
                    ),
                ),
                ("batch_number", models.CharField(blank=True, max_length=100, verbose_name="批次号")),
                (
                    "serial_numbers",
                    models.TextField(blank=True, help_text="多个序列号用换行分隔", verbose_name="序列号"),
                ),
                (
                    "conversion_unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="转采购时手动输入的含税单价",
                        max_digits=10,
                        null=True,
                        verbose_name="转采购单价",
                    ),
                ),
                (
                    "conversion_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="已转采购的数量",
                        max_digits=12,
                        verbose_name="转采购数量",
                    ),
                ),
                ("specifications", models.TextField(blank=True, verbose_name="规格要求")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "borrow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase.borrow",
                        verbose_name="借用单",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="产品",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "借用明细",
                "verbose_name_plural": "借用明细",
                "db_table": "purchase_borrow_item",
                "ordering": ["id"],
            },
        ),
    ]
