# Generated by Django 4.2.7 on 2026-01-11 05:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_inboundorder_outboundorder_outboundorderitem_and_more'),
        ('departments', '0002_initial'),
        ('suppliers', '0005_remove_supplier_contact_person_remove_supplier_email_and_more'),
        ('purchase', '0006_rename_fields_and_add_borrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinquiry',
            options={'ordering': ['-inquiry_date', '-created_at'], 'verbose_name': '采购询价单', 'verbose_name_plural': '采购询价单'},
        ),
        migrations.AlterModelOptions(
            name='purchaseinquiryitem',
            options={'ordering': ['id'], 'verbose_name': '询价单明细', 'verbose_name_plural': '询价单明细'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'ordering': ['id'], 'verbose_name': '采购订单明细', 'verbose_name_plural': '采购订单明细'},
        ),
        migrations.AlterModelOptions(
            name='purchasereceipt',
            options={'ordering': ['-receipt_date', '-created_at'], 'verbose_name': '采购收货单', 'verbose_name_plural': '采购收货单'},
        ),
        migrations.AlterModelOptions(
            name='purchasereceiptitem',
            options={'ordering': ['id'], 'verbose_name': '收货单明细', 'verbose_name_plural': '收货单明细'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequestitem',
            options={'ordering': ['id'], 'verbose_name': '采购申请明细', 'verbose_name_plural': '采购申请明细'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturn',
            options={'ordering': ['-return_date', '-created_at'], 'verbose_name': '采购退货单', 'verbose_name_plural': '采购退货单'},
        ),
        migrations.AlterModelOptions(
            name='purchasereturnitem',
            options={'ordering': ['id'], 'verbose_name': '退货单明细', 'verbose_name_plural': '退货单明细'},
        ),
        migrations.AlterModelOptions(
            name='supplierquotationitem',
            options={'ordering': ['id'], 'verbose_name': '报价单明细', 'verbose_name_plural': '报价单明细'},
        ),
        migrations.RemoveField(
            model_name='purchaseinquiry',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='purchaseinquiry',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='purchaseinquiry',
            name='department',
        ),
        migrations.RemoveField(
            model_name='purchaseinquiry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchaseinquiry',
            name='internal_notes',
        ),
        migrations.RemoveField(
            model_name='purchaseinquiry',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='purchaseinquiry',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchaseinquiry',
            name='purchase_request',
        ),
        migrations.RemoveField(
            model_name='purchaseinquiry',
            name='title',
        ),
        migrations.RemoveField(
            model_name='purchaseinquiry',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='purchaseinquiryitem',
            name='preferred_supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseinquiryitem',
            name='quality_requirements',
        ),
        migrations.RemoveField(
            model_name='purchaseinquiryitem',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='qualityinspection',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='qualityinspection',
            name='pass_rate',
        ),
        migrations.RemoveField(
            model_name='qualityinspection',
            name='product',
        ),
        migrations.RemoveField(
            model_name='qualityinspection',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='qualityinspection',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='qualityinspection',
            name='source_number',
        ),
        migrations.RemoveField(
            model_name='qualityinspection',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='qualityinspectionitem',
            name='inspection_item',
        ),
        migrations.RemoveField(
            model_name='qualityinspectionitem',
            name='method',
        ),
        migrations.RemoveField(
            model_name='qualityinspectionitem',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='delivery_period',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='evaluation_notes',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='evaluation_score',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='quality_certificate',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='supplierquotation',
            name='warranty_period',
        ),
        migrations.RemoveField(
            model_name='supplierquotationitem',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='supplierquotationitem',
            name='delivery_period',
        ),
        migrations.RemoveField(
            model_name='supplierquotationitem',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='supplierquotationitem',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='supplierquotationitem',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='supplierquotationitem',
            name='min_order_quantity',
        ),
        migrations.RemoveField(
            model_name='supplierquotationitem',
            name='model',
        ),
        migrations.RemoveField(
            model_name='supplierquotationitem',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='supplierquotationitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='supplierquotationitem',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='purchaseinquiry',
            name='converted_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_inquiry', to='purchase.purchaseorder', verbose_name='转换的采购订单'),
        ),
        migrations.AddField(
            model_name='purchaseinquiry',
            name='suppliers',
            field=models.ManyToManyField(related_name='purchase_inquiries', to='suppliers.supplier', verbose_name='询价供应商'),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='conclusion',
            field=models.TextField(blank=True, verbose_name='质检结论'),
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='receipt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='purchase.purchasereceipt', verbose_name='收货单'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualityinspection',
            name='total_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='检验数量'),
        ),
        migrations.AddField(
            model_name='qualityinspectionitem',
            name='inspection_method',
            field=models.CharField(blank=True, max_length=200, verbose_name='检验方法'),
        ),
        migrations.AddField(
            model_name='qualityinspectionitem',
            name='inspection_standard',
            field=models.TextField(blank=True, verbose_name='检验标准'),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='承诺交期'),
        ),
        migrations.AddField(
            model_name='supplierquotation',
            name='delivery_terms',
            field=models.CharField(blank=True, max_length=200, verbose_name='交货条款'),
        ),
        migrations.AddField(
            model_name='supplierquotationitem',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='交货日期'),
        ),
        migrations.AddField(
            model_name='supplierquotationitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='小计'),
        ),
        migrations.AlterField(
            model_name='purchaseinquiry',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='采购员'),
        ),
        migrations.AlterField(
            model_name='purchaseinquiry',
            name='selected_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_inquiry', to='purchase.supplierquotation', verbose_name='选定报价'),
        ),
        migrations.AlterField(
            model_name='purchaseinquiry',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('sent', '已发送'), ('quoted', '已报价'), ('selected', '已选定'), ('ordered', '已转订单'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='purchaseinquiryitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='询价数量'),
        ),
        migrations.AlterField(
            model_name='purchaseinquiryitem',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='目标价格'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_receipts', to=settings.AUTH_USER_MODEL, verbose_name='质检员'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='质检日期'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='overall_quality',
            field=models.CharField(blank=True, max_length=100, verbose_name='总体质量'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_receipts', to=settings.AUTH_USER_MODEL, verbose_name='收货人'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='status',
            field=models.CharField(choices=[('pending', '待收货'), ('partial', '部分收货'), ('received', '已收货'), ('inspecting', '质检中'), ('accepted', '已验收'), ('rejected', '已拒收')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='purchasereceipt',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse', verbose_name='收货仓库'),
        ),
        migrations.AlterField(
            model_name='purchasereceiptitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.location', verbose_name='存放位置'),
        ),
        migrations.AlterField(
            model_name='purchasereceiptitem',
            name='quality_status',
            field=models.CharField(default='pending', max_length=20, verbose_name='质量状态'),
        ),
        migrations.AlterField(
            model_name='purchasereceiptitem',
            name='received_quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='收货数量'),
        ),
        migrations.AlterField(
            model_name='purchasereceiptitem',
            name='serial_numbers',
            field=models.TextField(blank=True, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='converted_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='purchase.purchaseorder', verbose_name='转换的采购订单'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department', verbose_name='申请部门'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='purpose',
            field=models.TextField(blank=True, verbose_name='采购目的'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='required_date',
            field=models.DateField(blank=True, null=True, verbose_name='需求日期'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已审核'), ('ordered', '已转订单'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预估单价'),
        ),
        migrations.AlterField(
            model_name='purchaserequestitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='申请数量'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='purchase.purchaseorder', verbose_name='采购订单'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='reason',
            field=models.CharField(choices=[('quality', '质量问题'), ('quantity', '数量不符'), ('damage', '货物损坏'), ('specification', '规格不符'), ('other', '其他原因')], max_length=20, verbose_name='退货原因'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='purchase.purchasereceipt', verbose_name='收货单'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已审核'), ('returned', '已退货'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchaseorderitem', verbose_name='订单明细'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='退货数量'),
        ),
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='qualityinspection',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_inspections', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='qualityinspection',
            name='inspection_date',
            field=models.DateField(verbose_name='检验日期'),
        ),
        migrations.AlterField(
            model_name='qualityinspection',
            name='notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='qualityinspection',
            name='result',
            field=models.CharField(blank=True, choices=[('pass', '合格'), ('fail', '不合格'), ('conditional', '有条件通过')], max_length=20, null=True, verbose_name='检验结果'),
        ),
        migrations.AlterField(
            model_name='qualityinspection',
            name='status',
            field=models.CharField(choices=[('pending', '待质检'), ('in_progress', '质检中'), ('passed', '合格'), ('failed', '不合格'), ('conditional', '有条件通过'), ('approved', '已批准')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='qualityinspectionitem',
            name='actual_value',
            field=models.TextField(blank=True, verbose_name='实测值'),
        ),
        migrations.AlterField(
            model_name='qualityinspectionitem',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_items', to='purchase.qualityinspection', verbose_name='质检单'),
        ),
        migrations.AlterField(
            model_name='qualityinspectionitem',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=200, verbose_name='付款条款'),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='quotation_date',
            field=models.DateField(blank=True, null=True, verbose_name='报价日期'),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='status',
            field=models.CharField(choices=[('pending', '待报价'), ('submitted', '已提交'), ('selected', '已选定'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='报价总额'),
        ),
        migrations.AlterField(
            model_name='supplierquotation',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='有效期至'),
        ),
        migrations.AlterField(
            model_name='supplierquotationitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='报价数量'),
        ),
        migrations.AlterField(
            model_name='supplierquotationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='报价单价'),
        ),
    ]
