# Generated by Django 4.2.7 on 2026-01-14 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0005_remove_supplier_contact_person_remove_supplier_email_and_more"),
        ("purchase", "0009_remove_quality_inspection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_orders",
                to="suppliers.supplier",
                verbose_name="供应商",
            ),
        ),
    ]
