# Generated by Django 5.0.9 on 2026-01-15 03:17

from django.db import migrations, models


def migrate_order_statuses(apps, schema_editor):
    """迁移采购订单状态"""
    PurchaseOrder = apps.get_model('purchase', 'PurchaseOrder')

    # 状态映射关系
    status_mapping = {
        'draft': 'draft',              # 草稿 → 草稿
        'pending': 'draft',            # 待审核 → 草稿
        'approved': 'approved',        # 已审核 → 已审核
        'sent': 'approved',            # 已发送 → 已审核（已发送说明已通过审核）
        'confirmed': 'approved',       # 已确认 → 已审核（已确认说明已通过审核）
        'partial_received': 'partial_received',  # 部分收货 → 部分收货
        'received': 'fully_received',  # 已收货 → 全部收货
        'completed': 'invoiced',       # 已完成 → 已开票（简化处理）
        'cancelled': 'draft',          # 已取消 → 草稿（重新激活）
    }

    for order in PurchaseOrder.objects.all():
        old_status = order.status
        new_status = status_mapping.get(old_status, 'draft')
        if old_status != new_status:
            order.status = new_status
            order.save(update_fields=['status'])


def reverse_migrate_order_statuses(apps, schema_editor):
    """回滚采购订单状态迁移"""
    PurchaseOrder = apps.get_model('purchase', 'PurchaseOrder')

    # 反向状态映射
    reverse_status_mapping = {
        'draft': 'pending',            # 草稿 → 待审核（回滚到待审核）
        'approved': 'approved',        # 已审核 → 已审核
        'partial_received': 'partial_received',  # 部分收货 → 部分收货
        'fully_received': 'received',  # 全部收货 → 已收货
        'invoiced': 'completed',       # 已开票 → 已完成
        'paid': 'completed',           # 已付款 → 已完成
    }

    for order in PurchaseOrder.objects.all():
        old_status = order.status
        new_status = reverse_status_mapping.get(old_status, 'pending')
        if old_status != new_status:
            order.status = new_status
            order.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_allow_null_supplier_in_order'),
    ]

    operations = [
        # 先执行数据迁移，将旧状态映射到新状态
        migrations.RunPython(migrate_order_statuses, reverse_migrate_order_statuses),
        # 然后修改字段定义
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', '草稿'),
                    ('approved', '已审核'),
                    ('partial_received', '部分收货'),
                    ('fully_received', '全部收货'),
                    ('invoiced', '已开票'),
                    ('paid', '已付款')
                ],
                default='draft',
                max_length=20,
                verbose_name='订单状态'
            ),
        ),
    ]
