# Generated by Django 4.2.7 on 2026-01-22 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0012_restore_borrow_conversion_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowitem",
            name="borrowed_quantity",
            field=models.IntegerField(
                default=0, help_text="借用入库确认时累计的已借用数量（用于归还和转采购限制）", verbose_name="累计已借用数量"
            ),
        ),
        migrations.AlterField(
            model_name="borrow",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("approved", "已审核"),
                    ("borrowed", "借用中"),
                    ("completed", "已完成"),
                ],
                default="draft",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="borrowitem",
            name="conversion_quantity",
            field=models.IntegerField(default=0, help_text="已转采购的数量", verbose_name="转采购数量"),
        ),
        migrations.AlterField(
            model_name="borrowitem",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)], verbose_name="借用数量"
            ),
        ),
        migrations.AlterField(
            model_name="borrowitem",
            name="returned_quantity",
            field=models.IntegerField(default=0, verbose_name="已归还数量"),
        ),
        migrations.AlterField(
            model_name="purchaseinquiryitem",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)], verbose_name="询价数量"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)], verbose_name="数量"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="received_quantity",
            field=models.IntegerField(default=0, verbose_name="已收货数量"),
        ),
        migrations.AlterField(
            model_name="purchasereceiptitem",
            name="received_quantity",
            field=models.IntegerField(default=0, verbose_name="收货数量"),
        ),
        migrations.AlterField(
            model_name="purchaserequestitem",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)], verbose_name="申请数量"
            ),
        ),
        migrations.AlterField(
            model_name="purchasereturnitem",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)], verbose_name="退货数量"
            ),
        ),
        migrations.AlterField(
            model_name="supplierquotationitem",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)], verbose_name="报价数量"
            ),
        ),
    ]
