# Generated by Django 5.0.9 on 2026-02-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0018_add_borrow_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2, default=13, max_digits=5, verbose_name="税率(%)"
            ),
        ),
    ]
