# Generated by Django 5.0.9 on 2026-02-11 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0014_remove_supplieraccount_supplier_account_sup_status_due_idx"),
        ("purchase", "0019_set_default_tax_rate_13"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_orders",
                to="finance.invoice",
                verbose_name="关联发票",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="invoiced_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="开票时间"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="invoiced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoiced_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="开票人",
            ),
        ),
    ]
