# Generated by Django 5.0.9 on 2026-02-11 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0020_add_invoice_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="cancellation_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="取消时间"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="cancellation_reason",
            field=models.TextField(blank=True, verbose_name="取消原因"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="取消人",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="void_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="作废时间"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="void_reason",
            field=models.TextField(blank=True, verbose_name="作废原因"),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voided_orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作废人",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("approved", "已审核"),
                    ("partial_received", "部分收货"),
                    ("fully_received", "全部收货"),
                    ("invoiced", "已开票"),
                    ("paid", "已付款"),
                    ("cancelled", "已取消"),
                    ("voided", "已作废"),
                ],
                default="draft",
                max_length=20,
                verbose_name="订单状态",
            ),
        ),
    ]
