# Generated by Django 5.1 on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0021_purchaseorder_cancellation_date_and_more"),
    ]

    operations = [
        # 删除作废相关字段
        migrations.RemoveField(
            model_name="purchaseorder",
            name="void_reason",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="void_date",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="voided_by",
        ),
        # 修改状态选项，移除 'voided'
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("approved", "已审核"),
                    ("partial_received", "部分收货"),
                    ("fully_received", "全部收货"),
                    ("invoiced", "已开票"),
                    ("paid", "已付款"),
                    ("cancelled", "已取消"),
                ],
                default="draft",
                max_length=20,
                verbose_name="订单状态",
            ),
        ),
    ]
