# Generated by Django 5.1 on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0022_remove_void_fields"),
        ("finance", "0019_add_credit_note_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasereturn",
            name="credit_note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="purchase_returns",
                to="finance.invoice",
                verbose_name="红字发票",
            ),
        ),
    ]
