# Generated by Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0023_add_credit_note_to_return"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="cancellation_reason",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="cancellation_date",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="cancelled_by",
        ),
    ]
