# Generated by Django 5.0.9 on 2026-01-26 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_rename_ai_conversa_user_id_d9cb9e_idx_ai_conversa_user_id_948536_idx_and_more'),
        ('customers', '0005_remove_customer_contact_person_remove_customer_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodelconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('baidu', '百度文心一言'), ('aliyun', '阿里通义千问'), ('tencent', '腾讯混元'), ('zhipu', '智谱AI'), ('moonshot', 'Moonshot'), ('deepseek', 'DeepSeek'), ('mock', 'Mock（测试用）'), ('google', 'Google Gemini'), ('azure_openai', 'Microsoft Azure OpenAI'), ('aws_bedrock', 'AWS Bedrock'), ('groq', 'Groq'), ('huggingface', 'Hugging Face'), ('cohere', 'Cohere'), ('mistral', 'Mistral'), ('perplexity', 'Perplexity'), ('together', 'Together AI'), ('openrouter', 'OpenRouter')], max_length=50, verbose_name='提供商'),
        ),
        migrations.CreateModel(
            name='CustomerAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('system_prompt', models.TextField(blank=True, help_text='自定义系统提示词，留空则使用默认提示词', verbose_name='系统提示词')),
                ('permission_level', models.CharField(choices=[('read_only', '只读'), ('read_write', '读写'), ('full_access', '完全访问')], default='read_only', help_text='客户 AI 助手的权限级别', max_length=20, verbose_name='权限级别')),
                ('allowed_tools', models.JSONField(blank=True, default=list, help_text='允许客户 AI 助手使用的工具列表，留空则使用默认工具集', verbose_name='允许的工具')),
                ('blocked_tools', models.JSONField(blank=True, default=list, help_text='明确阻止的工具列表，优先级高于 allowed_tools', verbose_name='阻止的工具')),
                ('max_conversation_turns', models.IntegerField(default=50, help_text='单次会话的最大对话轮数', verbose_name='最大对话轮数')),
                ('max_conversation_duration', models.IntegerField(default=60, help_text='单次会话的最长持续时间', verbose_name='最大会话时长(分钟)')),
                ('enable_tool_calling', models.BooleanField(default=True, help_text='是否允许 AI 助手调用工具', verbose_name='启用工具调用')),
                ('enable_data_query', models.BooleanField(default=True, help_text='是否允许查询客户数据', verbose_name='启用数据查询')),
                ('enable_data_modification', models.BooleanField(default=False, help_text='是否允许修改客户数据（需要 full_access 权限）', verbose_name='启用数据修改')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('total_conversations', models.IntegerField(default=0, verbose_name='总会话数')),
                ('total_messages', models.IntegerField(default=0, verbose_name='总消息数')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='customers.customer', verbose_name='客户')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='删除人')),
                ('model_config', models.ForeignKey(blank=True, help_text='留空则使用全局默认配置', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_configs', to='ai_assistant.aimodelconfig', verbose_name='AI 模型配置')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '客户 AI 配置',
                'verbose_name_plural': '客户 AI 配置',
                'db_table': 'customer_ai_config',
                'ordering': ['customer__name'],
                'indexes': [models.Index(fields=['customer'], name='customer_ai_custome_668246_idx'), models.Index(fields=['is_active'], name='customer_ai_is_acti_f47e19_idx'), models.Index(fields=['permission_level'], name='customer_ai_permiss_872b24_idx')],
            },
        ),
    ]
