#!/bin/bash

# 采购退货单财务记录可见性修复验证脚本

echo "==================================="
echo "采购退货单财务记录可见性修复验证"
echo "==================================="
echo ""

echo "1️⃣ 验证代码注释术语修复..."
echo "----------------------------"
grep -A 5 "案例1：全收货场景" apps/purchase/views.py | grep "负应付账款" && echo "✅ 案例1术语修复正确" || echo "❌ 案例1术语修复失败"
grep -A 5 "案例3：未全收货" apps/purchase/views.py | grep "负应付账款" && echo "✅ 案例3术语修复正确" || echo "❌ 案例3术语修复失败"
echo ""

echo "2️⃣ 验证负应付说明添加..."
echo "----------------------------"
grep -c "负应付说明" templates/modules/finance/supplier_account_list.html > /dev/null && echo "✅ 负应付说明已添加" || echo "❌ 负应付说明未添加"
echo ""

echo "3️⃣ 验证退货明细列添加..."
echo "----------------------------"
grep -c "退货明细" templates/modules/finance/supplier_account_list.html > /dev/null && echo "✅ 退货明细列已添加" || echo "❌ 退货明细列未添加"
echo ""

echo "4️⃣ 验证财务记录链接添加..."
echo "----------------------------"
grep -c "查看应付账款记录" templates/modules/purchase/return_detail.html > /dev/null && echo "✅ 财务记录链接已添加" || echo "❌ 财务记录链接未添加"
echo ""

echo "==================================="
echo "✅ 所有修复已完成！"
echo "==================================="
echo ""
echo "📋 验证步骤："
echo ""
echo "1. 启动开发服务器："
echo "   python manage.py runserver"
echo ""
echo "2. 访问供应商应付账款列表："
echo "   http://127.0.0.1:8000/finance/supplier-accounts/"
echo "   ✓ 检查页面顶部是否有蓝色提示框说明负应付概念"
echo "   ✓ 检查列表中是否显示'退货明细'列"
echo "   ✓ 确认能看到ID=3的记录（余额¥6000.00）"
echo ""
echo "3. 访问退货详情页面："
echo "   http://127.0.0.1:8000/purchase/returns/1/"
echo "   ✓ 检查是否有'查看应付账款记录'按钮（已审核/已退货/已完成状态）"
echo ""
echo "4. 点击'查看应付账款记录'按钮："
echo "   ✓ 跳转到 /finance/supplier-accounts/3/"
echo "   ✓ 能看到2条明细：收货正应付(¥12000) + 退货负应付(-¥6000)"
echo ""
echo "==================================="
