# Generated by Django 5.0.9 on 2026-01-28 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0004_add_default_unit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EcommPlatform",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "platform_type",
                    models.CharField(
                        choices=[("taobao", "淘宝"), ("alibaba", "1688")],
                        max_length=20,
                        verbose_name="平台类型",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="平台名称")),
                ("base_url", models.URLField(verbose_name="基础URL")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "电商平台",
                "verbose_name_plural": "电商平台",
                "db_table": "ecomm_platform",
            },
        ),
        migrations.CreateModel(
            name="EcommProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "external_id",
                    models.CharField(db_index=True, max_length=200, verbose_name="平台商品ID"),
                ),
                (
                    "external_url",
                    models.URLField(max_length=1000, verbose_name="商品链接"),
                ),
                (
                    "raw_data",
                    models.JSONField(blank=True, default=dict, verbose_name="原始数据"),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "待同步"),
                            ("synced", "已同步"),
                            ("failed", "同步失败"),
                            ("delisted", "已下架"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="同步状态",
                    ),
                ),
                (
                    "woo_product_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="WooCommerce中的产品ID",
                        null=True,
                        verbose_name="WooCommerce产品ID",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后同步时间"),
                ),
                (
                    "last_scraped_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后采集时间"),
                ),
                (
                    "is_delisted",
                    models.BooleanField(
                        default=False,
                        help_text="平台商品是否已下架",
                        verbose_name="是否下架",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="ecomm_sync.ecommplatform",
                        verbose_name="平台",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecomm_records",
                        to="products.product",
                        verbose_name="关联产品",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "电商商品",
                "verbose_name_plural": "电商商品",
                "db_table": "ecomm_product",
            },
        ),
        migrations.CreateModel(
            name="ProductChangeLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("price", "价格变更"),
                            ("stock", "库存变更"),
                            ("status", "状态变更"),
                            ("detail", "详情变更"),
                            ("new", "新增商品"),
                            ("delisted", "下架商品"),
                        ],
                        max_length=20,
                        verbose_name="变更类型",
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(blank=True, null=True, verbose_name="原值"),
                ),
                (
                    "new_value",
                    models.JSONField(blank=True, null=True, verbose_name="新值"),
                ),
                (
                    "synced_to_woo",
                    models.BooleanField(default=False, verbose_name="已同步Woo"),
                ),
                (
                    "woo_synced_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Woo同步时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "ecomm_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="ecomm_sync.ecommproduct",
                        verbose_name="电商商品",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品变更日志",
                "verbose_name_plural": "商品变更日志",
                "db_table": "ecomm_product_change_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncStrategy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="策略名称")),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("full", "全量同步"),
                            ("incremental", "增量同步"),
                            ("price_only", "仅价格"),
                        ],
                        max_length=20,
                        verbose_name="策略类型",
                    ),
                ),
                (
                    "update_fields",
                    models.JSONField(
                        default=list,
                        help_text='如：["price", "stock", "status"]',
                        verbose_name="更新字段",
                    ),
                ),
                (
                    "sync_interval_hours",
                    models.PositiveIntegerField(default=24, verbose_name="同步间隔(小时)"),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后同步时间"),
                ),
                (
                    "next_sync_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="下次同步时间"),
                ),
                (
                    "batch_size",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="每次同步的商品数量",
                        verbose_name="批量大小",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategies",
                        to="ecomm_sync.ecommplatform",
                        verbose_name="平台",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "同步策略",
                "verbose_name_plural": "同步策略",
                "db_table": "ecomm_sync_strategy",
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("scrape", "采集"),
                            ("transform", "转换"),
                            ("sync", "同步到WooCommerce"),
                            ("incremental", "增量同步"),
                            ("full_sync", "全量同步"),
                        ],
                        max_length=20,
                        verbose_name="日志类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("partial", "部分成功"),
                        ],
                        default="running",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "records_processed",
                    models.PositiveIntegerField(default=0, verbose_name="处理记录数"),
                ),
                (
                    "records_succeeded",
                    models.PositiveIntegerField(default=0, verbose_name="成功记录数"),
                ),
                (
                    "records_failed",
                    models.PositiveIntegerField(default=0, verbose_name="失败记录数"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "execution_time",
                    models.FloatField(default=0, verbose_name="执行时间(秒)"),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="存储同步过程中的详细信息",
                        verbose_name="详细信息",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="ecomm_sync.ecommplatform",
                        verbose_name="平台",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_logs",
                        to="ecomm_sync.syncstrategy",
                        verbose_name="同步策略",
                    ),
                ),
            ],
            options={
                "verbose_name": "同步日志",
                "verbose_name_plural": "同步日志",
                "db_table": "ecomm_sync_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WooShopConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                ("shop_url", models.URLField(verbose_name="店铺URL")),
                (
                    "shop_name",
                    models.CharField(blank=True, max_length=200, verbose_name="店铺名称"),
                ),
                (
                    "consumer_key",
                    models.CharField(max_length=200, verbose_name="Consumer Key"),
                ),
                (
                    "consumer_secret",
                    models.CharField(max_length=200, verbose_name="Consumer Secret"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "default_category_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="WooCommerce中的默认商品分类ID",
                        null=True,
                        verbose_name="默认分类ID",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "WooCommerce配置",
                "verbose_name_plural": "WooCommerce配置",
                "db_table": "ecomm_woo_shop",
            },
        ),
        migrations.AddIndex(
            model_name="ecommproduct",
            index=models.Index(
                fields=["platform", "sync_status"],
                name="ecomm_produ_platfor_af6b03_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ecommproduct",
            index=models.Index(fields=["external_id"], name="ecomm_produ_externa_421be3_idx"),
        ),
        migrations.AddIndex(
            model_name="ecommproduct",
            index=models.Index(fields=["sync_status"], name="ecomm_produ_sync_st_387629_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="ecommproduct",
            unique_together={("platform", "external_id")},
        ),
        migrations.AddIndex(
            model_name="productchangelog",
            index=models.Index(
                fields=["ecomm_product", "-created_at"],
                name="ecomm_produ_ecomm_p_c24904_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productchangelog",
            index=models.Index(
                fields=["change_type", "-created_at"],
                name="ecomm_produ_change__2f432e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productchangelog",
            index=models.Index(
                fields=["synced_to_woo", "-created_at"],
                name="ecomm_produ_synced__6933a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["-created_at", "status"], name="ecomm_sync__created_6065c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["platform", "-created_at"],
                name="ecomm_sync__platfor_952a9a_idx",
            ),
        ),
    ]
