# Generated by Django 5.0.9 on 2026-01-31 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecomm_sync", "0002_alter_ecommplatform_id_alter_ecommproduct_id_and_more"),
        ("products", "0004_add_default_unit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("amazon", "Amazon"),
                            ("ebay", "eBay"),
                            ("aliexpress", "速卖通"),
                            ("lazada", "Lazada"),
                            ("woo", "WooCommerce"),
                            ("shopify", "Shopify"),
                        ],
                        max_length=20,
                        verbose_name="账号类型",
                    ),
                ),
                (
                    "account_name",
                    models.CharField(max_length=200, verbose_name="账号名称"),
                ),
                (
                    "platform_user_id",
                    models.CharField(blank=True, max_length=200, verbose_name="平台用户ID"),
                ),
                (
                    "auth_config",
                    models.JSONField(
                        default=dict,
                        help_text="加密存储的认证信息",
                        verbose_name="认证配置",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Token过期时间"),
                ),
                (
                    "rate_limit_remaining",
                    models.IntegerField(
                        default=0,
                        help_text="平台API剩余调用次数",
                        verbose_name="剩余调用次数",
                    ),
                ),
                (
                    "rate_limit_reset_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="限流重置时间"),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后同步时间"),
                ),
                ("last_error", models.TextField(blank=True, verbose_name="最后错误")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="ecomm_sync.ecommplatform",
                        verbose_name="平台",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "平台账号",
                "verbose_name_plural": "平台账号",
                "db_table": "ecomm_platform_account",
            },
        ),
        migrations.CreateModel(
            name="APICallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                ("endpoint", models.CharField(max_length=500, verbose_name="API端点")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=10,
                        verbose_name="HTTP方法",
                    ),
                ),
                (
                    "request_data",
                    models.JSONField(blank=True, default=dict, verbose_name="请求数据"),
                ),
                (
                    "response_status",
                    models.IntegerField(blank=True, null=True, verbose_name="响应状态码"),
                ),
                (
                    "response_data",
                    models.JSONField(blank=True, default=dict, verbose_name="响应数据"),
                ),
                (
                    "execution_time",
                    models.FloatField(default=0, verbose_name="执行时间(秒)"),
                ),
                ("success", models.BooleanField(default=True, verbose_name="是否成功")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_logs",
                        to="ecomm_sync.ecommplatform",
                        verbose_name="平台",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_logs",
                        to="ecomm_sync.platformaccount",
                        verbose_name="账号",
                    ),
                ),
            ],
            options={
                "verbose_name": "API调用日志",
                "verbose_name_plural": "API调用日志",
                "db_table": "ecomm_api_call_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "platform_order_id",
                    models.CharField(db_index=True, max_length=200, verbose_name="平台订单号"),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("pending", "待付款"),
                            ("paid", "已付款"),
                            ("processing", "处理中"),
                            ("shipped", "已发货"),
                            ("delivered", "已送达"),
                            ("cancelled", "已取消"),
                            ("refunded", "已退款"),
                        ],
                        max_length=20,
                        verbose_name="订单状态",
                    ),
                ),
                (
                    "order_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="订单金额"),
                ),
                (
                    "currency",
                    models.CharField(default="CNY", max_length=10, verbose_name="货币"),
                ),
                (
                    "buyer_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="买家邮箱"),
                ),
                (
                    "buyer_name",
                    models.CharField(blank=True, max_length=200, verbose_name="买家姓名"),
                ),
                (
                    "buyer_phone",
                    models.CharField(blank=True, max_length=50, verbose_name="买家电话"),
                ),
                (
                    "shipping_address",
                    models.JSONField(blank=True, default=dict, verbose_name="收货地址"),
                ),
                (
                    "raw_data",
                    models.JSONField(blank=True, default=dict, verbose_name="原始数据"),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "待同步"),
                            ("synced", "已同步"),
                            ("syncing", "同步中"),
                            ("failed", "同步失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="同步状态",
                    ),
                ),
                (
                    "synced_to_erp",
                    models.BooleanField(default=False, verbose_name="已同步到ERP"),
                ),
                (
                    "synced_to_platform",
                    models.BooleanField(default=True, verbose_name="已同步到平台"),
                ),
                (
                    "erp_order_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=200,
                        verbose_name="ERP订单ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=200, verbose_name="快递单号"),
                ),
                ("sync_error", models.TextField(blank=True, verbose_name="同步错误")),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="ecomm_sync.platformaccount",
                        verbose_name="账号",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="ecomm_sync.ecommplatform",
                        verbose_name="平台",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "平台订单",
                "verbose_name_plural": "平台订单",
                "db_table": "ecomm_platform_order",
            },
        ),
        migrations.CreateModel(
            name="PlatformOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "sku",
                    models.CharField(db_index=True, max_length=100, verbose_name="SKU"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=500, verbose_name="商品名称"),
                ),
                ("quantity", models.IntegerField(verbose_name="数量")),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="单价"),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="总价"),
                ),
                (
                    "platform_product_id",
                    models.CharField(blank=True, max_length=200, verbose_name="平台商品ID"),
                ),
                (
                    "raw_data",
                    models.JSONField(blank=True, default=dict, verbose_name="原始数据"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ecomm_sync.platformorder",
                        verbose_name="订单",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "平台订单商品",
                "verbose_name_plural": "平台订单商品",
                "db_table": "ecomm_platform_order_item",
            },
        ),
        migrations.CreateModel(
            name="ProductListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "platform_product_id",
                    models.CharField(db_index=True, max_length=200, verbose_name="平台商品ID"),
                ),
                (
                    "platform_sku",
                    models.CharField(blank=True, max_length=200, verbose_name="平台SKU"),
                ),
                (
                    "listing_title",
                    models.CharField(blank=True, max_length=500, verbose_name="Listing标题"),
                ),
                (
                    "listing_status",
                    models.CharField(
                        choices=[
                            ("onsale", "在售"),
                            ("offshelf", "已下架"),
                            ("pending", "待审核"),
                            ("rejected", "已拒绝"),
                        ],
                        max_length=20,
                        verbose_name="Listing状态",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="价格"),
                ),
                ("quantity", models.IntegerField(default=0, verbose_name="库存数量")),
                (
                    "woo_product_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="WooCommerce产品ID"
                    ),
                ),
                (
                    "sync_enabled",
                    models.BooleanField(default=True, verbose_name="启用同步"),
                ),
                (
                    "auto_update_price",
                    models.BooleanField(default=False, verbose_name="自动更新价格"),
                ),
                (
                    "auto_update_stock",
                    models.BooleanField(default=True, verbose_name="自动更新库存"),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最后同步时间"),
                ),
                ("sync_error", models.TextField(blank=True, verbose_name="同步错误")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="ecomm_sync.platformaccount",
                        verbose_name="账号",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="ecomm_sync.ecommplatform",
                        verbose_name="平台",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品Listing",
                "verbose_name_plural": "产品Listing",
                "db_table": "ecomm_product_listing",
            },
        ),
        migrations.CreateModel(
            name="StockSyncQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[("push", "推送到平台"), ("pull", "从平台拉取")],
                        max_length=20,
                        verbose_name="同步类型",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="库存数量")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "max_retries",
                    models.IntegerField(default=3, verbose_name="最大重试次数"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理时间"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_sync_queues",
                        to="ecomm_sync.platformaccount",
                        verbose_name="账号",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="删除人",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_sync_queues",
                        to="ecomm_sync.ecommplatform",
                        verbose_name="平台",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_sync_queues",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新人",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存同步队列",
                "verbose_name_plural": "库存同步队列",
                "db_table": "ecomm_stock_sync_queue",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="platformaccount",
            index=models.Index(
                fields=["account_type", "is_active"],
                name="ecomm_platf_account_8b0961_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="platformaccount",
            index=models.Index(
                fields=["platform", "is_active"], name="ecomm_platf_platfor_4a1a40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="platformaccount",
            index=models.Index(fields=["-last_synced_at"], name="ecomm_platf_last_sy_d9d62b_idx"),
        ),
        migrations.AddIndex(
            model_name="apicalllog",
            index=models.Index(
                fields=["platform", "account", "-created_at"],
                name="ecomm_api_c_platfor_ee2fd1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apicalllog",
            index=models.Index(
                fields=["success", "-created_at"], name="ecomm_api_c_success_05de17_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apicalllog",
            index=models.Index(
                fields=["response_status", "-created_at"],
                name="ecomm_api_c_respons_8b24a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apicalllog",
            index=models.Index(fields=["endpoint"], name="ecomm_api_c_endpoin_a1bc30_idx"),
        ),
        migrations.AddIndex(
            model_name="platformorder",
            index=models.Index(
                fields=["platform", "order_status"],
                name="ecomm_platf_platfor_aa11c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="platformorder",
            index=models.Index(
                fields=["platform", "sync_status"],
                name="ecomm_platf_platfor_7e5089_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="platformorder",
            index=models.Index(fields=["-created_at"], name="ecomm_platf_created_221672_idx"),
        ),
        migrations.AddIndex(
            model_name="platformorder",
            index=models.Index(fields=["buyer_email"], name="ecomm_platf_buyer_e_bcb449_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="platformorder",
            unique_together={("platform", "platform_order_id")},
        ),
        migrations.AddIndex(
            model_name="platformorderitem",
            index=models.Index(fields=["order", "sku"], name="ecomm_platf_order_i_3e07dc_idx"),
        ),
        migrations.AddIndex(
            model_name="platformorderitem",
            index=models.Index(fields=["sku"], name="ecomm_platf_sku_510d78_idx"),
        ),
        migrations.AddIndex(
            model_name="productlisting",
            index=models.Index(
                fields=["product", "platform", "listing_status"],
                name="ecomm_produ_product_90f514_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productlisting",
            index=models.Index(
                fields=["platform", "account", "listing_status"],
                name="ecomm_produ_platfor_69cce1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productlisting",
            index=models.Index(fields=["-last_synced_at"], name="ecomm_produ_last_sy_e9f1b0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productlisting",
            unique_together={("platform", "account", "platform_product_id")},
        ),
        migrations.AddIndex(
            model_name="stocksyncqueue",
            index=models.Index(
                fields=["platform", "status"], name="ecomm_stock_platfor_c1cc7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocksyncqueue",
            index=models.Index(
                fields=["status", "created_at"], name="ecomm_stock_status_111c2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocksyncqueue",
            index=models.Index(
                fields=["sync_type", "status"], name="ecomm_stock_sync_ty_5e3d46_idx"
            ),
        ),
    ]
